Added URL rewrites data to the product interface
magento/graphql-ce pull request #107
Opened 2018-06-30 13:47 UTC by rogyar

### Description
Added URL rewrites data to the GraphQL product interface. So, now we have a possibility to fetch all URL rewrites for a product with request URL data and target URL parameters.

Also, the old `UrlRewrite` resolver has been renamed to `EntityUrl` to make the class name match its purpose. 

### Fixed Issues (if relevant)
1. https://github.com/magento/graphql-ce/issues/84

### Manual testing scenarios
- Create a product with name "configurable" and assign it to a category
- Use the following request to fetch the product data:

```
{
    products (search:"conf") {
        items {
            name,
            sku,
            description,
          	url_rewrites {
              url,
              parameters {
                name,
                value
              }
            }
        }
    }
}
```

- You should see 2 URL rewrites in the response like in the following example:

```
{
  "data": {
    "products": {
      "items": [
        {
          "name": "Configurable",
          "sku": "Configurable",
          "description": null,
          "url_rewrites": [
            {
              "url": "configurable.html",
              "parameters": [
                {
                  "name": "id",
                  "value": "5"
                }
              ]
            },
            {
              "url": "some-category/configurable.html",
              "parameters": [
                {
                  "name": "id",
                  "value": "5"
                },
                {
                  "name": "category",
                  "value": "3"
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
```

2018-07-26 14:57 UTC, vkublytskyi commented on app/code/Magento/UrlRewriteGraphQl/Model/Resolver/EntityUrl.php
> + * UrlRewrite field resolver, used for GraphQL request processing.
As EntityUrl and UrlRewrite are pretty similar it is better to describe their purpose in class comments (now both classes have same description so to understand what is needed source code should be explored)

2018-09-05 11:16 UTC, naydav commented on app/code/Magento/CatalogGraphQl/etc/schema.graphqls
> +    url_rewrites: [UrlRewrite] @doc(description: "URL rewrites list") @resolver(class: "Magento\\UrlRewriteGraphQl\\Model\\Resolver\\UrlRewrite")
Looks like we need to move all of this functionality to `CatalogUrlRewriteGraphQl`

2018-09-17 17:20 UTC, naydav requested changes

2018-09-17 17:20 UTC, naydav commented on app/code/Magento/UrlRewriteGraphQl/Model/Resolver/EntityUrl.php
> +        $this->valueFactory = $valueFactory;
Pls remove using Factory

2018-10-04 10:56 UTC, merged