magento/graphql-ce#808: [Test coverage] Add disabled variation of Configurable Product to cart
magento/graphql-ce pull request #1071
Opened 2019-11-27 14:19 UTC by sergiy-v

### Description (*)
Covered the following test cases:
```
Magento\GraphQl\ConfigurableProduct\AddConfigurableProductToCartTest
- testAddDisabledVariationToCart
- testOutOfStockVariationToCart
```

### Fixed Issues (if relevant)

1. #808 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-11-27 15:45 UTC, lenaorobei requested changes
Please address review comments and add `rollback` files.

2019-11-27 15:45 UTC, lenaorobei commented on dev/tests/integration/testsuite/Magento/ConfigurableProduct/_files/product_configurable_disable_first_child.php
> +<?php
Let's include `configurable` fixture here and disable child by `sku`.

2019-11-27 15:45 UTC, lenaorobei commented on dev/tests/integration/testsuite/Magento/ConfigurableProduct/_files/product_configurable_zero_qty_first_child.php
> +<?php
Let's include `configurable` fixture here and set zero quantity for the child by `sku`.

2019-11-28 16:35 UTC, sergiy-v commented
> Please address review comments and add `rollback` files.

The mentioned changes has been added, please check the result.
Thank you.

2019-12-02 15:51 UTC, lenaorobei commented
@magento run WebAPI Tests

2019-12-06 21:44 UTC, lenaorobei approved these changes

2019-12-06 21:46 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-6422](https://jira.corp.magento.com/browse/ENGCOM-6422) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-12-11 22:11 UTC, merged