Return product stock data
magento/graphql-ce pull request #125
Opened 2018-07-18 14:57 UTC by bartekszymanski

### Description

- Distinguish between "in-stock" and "out-of-stock" products on storefront (if "display out-of-stock products = Yes)

- Show "Only X Left" or "Low Stock" on PDP or PLP when the product's stock is below the configured threshold (Catalog > Inventory > Stock Options)

### Fixed Issues (if relevant)

magento/graphql-ce#23: Return product stock data

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-07-18 14:57 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=125) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=125) before we can accept your contribution.<br/>

2018-07-18 16:13 UTC, paliarush requested changes

2018-07-18 16:13 UTC, paliarush commented on app/code/Magento/CatalogInventoryGraphQl/Model/Resolver/OnlyXLeftInStockResolver.php
> +        $stockItem = $this->stockRegistry->getStockItem($product->getId());
Can we check if 'only X left' feature is enabled before performing any additional calculations?

2018-07-18 16:13 UTC, paliarush commented on app/code/Magento/CatalogInventoryGraphQl/Test/CatalogInventory/ProductOnlyXLeftInStockTest.php
> +namespace Magento\CatalogInventoryGraphQl\Test\CatalogInventory;
GraphQL functional tests must be placed under `dev/tests/api-functional/testsuite/Magento/GraphQl`, otherwise they will not be picked up by the builds. This is the difference between Unit vs other types of tests.

2018-07-18 16:13 UTC, paliarush commented on app/code/Magento/CatalogInventoryGraphQl/etc/schema.graphqls
> +    stock_status: Int @doc(description: "Stock status of the product") @resolver(class: "Magento\\CatalogInventoryGraphQl\\Model\\Resolver\\StockStatusProvider")
Please consider changing the type of `stock_status` to enum. See example [here](https://github.com/magento/magento2/blob/19dbdde998c136c557b14df1149c0ce48ff7060b/app/code/Magento/CatalogGraphQl/etc/schema.graphqls#L211)

2018-07-18 16:13 UTC, paliarush commented on app/code/Magento/CatalogInventoryGraphQl/Model/Resolver/OnlyXLeftInStockResolver.php
> +class OnlyXLeftInStockResolver implements ResolverInterface
Please document all classes/interfaces/methods. Documentation in tests is optional.

2018-07-18 16:13 UTC, paliarush commented on app/code/Magento/CatalogInventoryGraphQl/Test/CatalogInventory/ProductStockStatusTest.php
> +class ProductStockStatusTest extends GraphQlAbstract
Great job on tests!

2018-07-18 16:14 UTC, paliarush commented
@bartekszymanski thank you for the contribution. Please see several suggestions in the comments above.

2018-07-23 15:18 UTC, paliarush approved these changes

2018-07-23 15:18 UTC, paliarush commented on app/code/Magento/CatalogInventoryGraphQl/Model/Resolver/OnlyXLeftInStockResolver.php
> +     * {@inheritdoc}
It was actually correct before. But not a big deal, can leave as is.

2018-08-14 14:31 UTC, paliarush approved these changes

2018-09-11 03:11 UTC, merged