120 implement store configs coverage
magento/graphql-ce pull request #126
Opened 2018-07-18 19:57 UTC by VitaliyBoyko

### Description
Implemented StoreConfig graphql coverage

### Fixed Issues (if relevant)
1. magento/graphql-ce#120: Implement storeConfigs coverage

```
{
  storeConfigs{
      items{
        id,
    		code,
    		website_id,
    		locale,
    		base_currency_code,
    		default_display_currency_code,
    		timezone,
    		weight_unit,
    		base_url,
    		base_link_url,
    		base_static_url,
    		base_media_url,
    		secure_base_url,
    		secure_base_link_url,
    		secure_base_static_url,
    		secure_base_media_url 
      }
  }
}
```

2018-07-18 19:57 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=126) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=126) before we can accept your contribution.<br/>

2018-07-20 15:14 UTC, nuzil commented
Looks great! I will made some additional checks and if everything fine we can merge it

2018-07-20 21:22 UTC, nuzil requested changes

2018-07-20 21:22 UTC, nuzil commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Store/StoreConfigResolverTest.php
> +      items{
Can you please align test. Looks like you removed "items" on your last code update. Should be also removed here.

2018-07-23 15:41 UTC, nuzil approved these changes

2018-07-24 11:37 UTC, merged