Developed categories Endpoint for GraphQL
magento/graphql-ce pull request #149
Opened 2018-08-09 17:34 UTC by umarch06

### Description 
The categories endpoint returns categories collection with respect to the input provided that can be either search/filter.
This  endpoint contains all the code in existing Magento_CatalogGraphQl module. The **categories** endpoint expects *search*/*filter* attribute in the input similar to **products** endpoint.

In search query we need to input something similar to this query:

```
{
  categories
  (
		search:"Cat"
  ) {
    items {
      name
      level
      include_in_menu
      display_mode
      url_path
      created_at
      updated_at
      position
    }
  }
}

```

in return we can have the following response:

```
{
  "data": {
    "categories": {
      "items": [
        {
          "name": "Category 3.1.2",
          "level": 4,
          "include_in_menu": 1,
          "display_mode": "PRODUCTS",
          "url_path": "category-3/category-3-1/category-3-1-2",
          "created_at": "2018-07-10 09:19:02",
          "updated_at": "2018-07-10 10:10:29",
          "position": 1
        },
      ]
    }
  }
}
```

For retrieving categories through filters, we need the input similar to the following:

```
{
  categories
  (
      filter: {
      name: {like: "%Cat%"}
      level:{ gt : "0" }
    }
  ) {
    items {
      name
      level
      include_in_menu
      display_mode
      url_path
      created_at
      updated_at
      position
    }
  }
}

```
In the above scenario, we can have the following filters in the **filter** param:

> name: FilterTypeInput
> The category name. Customers use this name to identify the category.
> 
> description: FilterTypeInput
> Detailed information about the category. The value can include simple HTML tags.
> 
> created_at: FilterTypeInput
> Timestamp indicating when the category was created
> 
> updated_at: FilterTypeInput
> Timestamp indicating when the category was updated
> 
> is_anchor: FilterTypeInput
> The value can be true or false
> 
> level: FilterTypeInput
> The integer which define level of category
> 
> or: CategoryFilterInput
> The keyword required to perform a logical OR comparison

All the things are done in Magento_CatalogGraphQl module, somehow I needed to define virualType in **di.xml** of Magento_Catalog module for re-defining the filters, sorting and pagination for category collection as following:

```
<virtualType name="Magento\Catalog\Model\Api\SearchCriteria\CategoryCollectionProcessor" type="Magento\Eav\Model\Api\SearchCriteria\CollectionProcessor">
        <arguments>
            <argument name="processors" xsi:type="array">
                <item name="filters" xsi:type="object">Magento\Eav\Model\Api\SearchCriteria\CollectionProcessor\FilterProcessor</item>
                <item name="sorting" xsi:type="object">Magento\Framework\Api\SearchCriteria\CollectionProcessor\SortingProcessor</item>
                <item name="pagination" xsi:type="object">Magento\Framework\Api\SearchCriteria\CollectionProcessor\PaginationProcessor</item>
            </argument>
        </arguments>
    </virtualType>
```

### Manual testing scenarios
I tested the above listed scenarios and they can return the needed attributes. 
However, we cannot retrieve products within categories at this point, we need to create a resolver for that. Currently we have products resolver for a CategoryTree point only.

2018-08-09 17:35 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=149) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=149) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: adexandros<br/>:x: gelanivishal<br/>:x: umarch06

2018-08-13 12:13 UTC, naydav requested changes

2018-08-13 12:13 UTC, naydav commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Categories/DataProvider/Category.php
> +class Category
Need to use `\Magento\Catalog\Api\CategoryListInterface` instead of this class

2018-08-13 12:13 UTC, naydav commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Categories/DataProvider/Category/CollectionProcessorInterface.php
> +interface CollectionProcessorInterface
Need to use `\Magento\Catalog\Api\CategoryListInterface`

2019-04-04 21:48 UTC, naydav commented
@umarch06 
Hi Umar,
https://github.com/magento/graphql-ce/issues/567

we are going to create a new more efficient way for filtration and loading data.
Creation of Design Document is in progress.
So, doesn't make sense to continue work in the old way, need to wait to introduce a new mechanism and just after that continue work with this PR.

2019-04-24 20:53 UTC, naydav commented
Functionality postponed until the epic https://github.com/magento/graphql-ce/issues/567 is finished.

2019-04-24 20:53 UTC, closed without merging

2019-11-04 10:43 UTC, kriskate commented
Hi guys, shouldn't this be reopened, as #567 is done?
It would be really useful to filter categories, at least by `include_in_menu`