Allow changing logged in customers password with Graphql mutation
magento/graphql-ce pull request #150
Opened 2018-08-12 15:53 UTC by austris-argalis

### Description

Added a resolver which updates customer password. In response returns _Customer_ object (not sure whether this is necessary).

### Fixed Issues (if relevant)

1. magento/graphql-ce#54 : [Mutations] My Account: Change Password 

### Manual testing scenarios

1. Create a new user account from store front-end or admin
2. Acquire authorization with store (example uses session cookie)
3.  Execute a graphql query like:
`
curl -XPOST -H "Content-Type: application/json" -b PHPSESSID=d4d1cbf0ad346103fffc1b71d8059bc7 \
  -d '{"query": "mutation {changePassword(currentPassword: \"password\", newPassword: \"newPassword123\") {id, email, firstname, lastname}}","variables": [],"operationName": null}' \
  http://magento23.local/graphql
`
4. Ensure response has no errors and contain requested customer data

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-08-12 15:53 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=150) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=150) before we can accept your contribution.<br/>

2018-08-14 20:12 UTC, paliarush commented on app/code/Magento/CustomerGraphQl/etc/schema.graphqls
> +    changePassword(currentPassword: String!, newPassword: String!): Customer @resolver(class: "\\Magento\\CustomerGraphQl\\Model\\Resolver\\Customer\\Account\\ChangePassword") @doc(description:"Chang
Since this mutation is in global scope, it is better to name it `changeCustomerPassword`

2018-08-14 20:17 UTC, paliarush commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Customer/CustomerChangePasswordTest.php
> +    public function testGuestUserCannotChangePassword()
Would be nice to make sure that the password can be changed only if correct current password was specified.

2018-08-14 20:18 UTC, paliarush requested changes
@austris-argalis thank you for contribution, please see several comments above.

2018-08-15 18:41 UTC, austris-argalis commented
@paliarush thanks for review!
Renamed the mutation and added a new test case with a valid session but incorrect current pw in the change request.

2018-08-16 13:08 UTC, naydav commented
Hello, @austris-argalis 
Can you ping me (vnayda) in Slack channel?
Thanks

2018-08-16 14:37 UTC, paliarush approved these changes

2018-09-13 11:14 UTC, naydav commented
Hello, @austris-argalis 

Pls check `CustomerChangePasswordTest `
```
CustomerChangePasswordTest testCannotChangeWithIncorrectPassword History | REST EE | < 1 sec
-- | -- | --
Magento\GraphQl\Customer\CustomerChangePasswordTest::testCannotChangeWithIncorrectPassword Failed asserting that exception message 'GraphQL response contains errors: Internal server error ' matches '/The password doesn't match this account. Verify the password.*/'.
  | Failed | CustomerChangePasswordTest testChangeWeakPassword History | REST EE | < 1 sec
Magento\GraphQl\Customer\CustomerChangePasswordTest::testChangeWeakPassword Failed asserting that exception message 'GraphQL response contains errors: Internal server error ' matches '/Minimum of different classes of characters in password is.*/'.
  | Failed | CustomerChangePasswordTest testCannotChangeWithIncorrectPassword History | SOAP EE | < 1 sec
Magento\GraphQl\Customer\CustomerChangePasswordTest::testCannotChangeWithIncorrectPassword Failed asserting that exception message 'GraphQL response contains errors: Internal server error ' matches '/The password doesn't match this account. Verify the password.*/'.
  | Failed | CustomerChangePasswordTest testChangeWeakPassword History | SOAP EE | < 1 sec
Magento\GraphQl\Customer\CustomerChangePasswordTest::testChangeWeakPassword Failed asserting that exception message 'GraphQL response contains errors: Internal server error ' matches '/Minimum of different classes of characters in password is.*/'.


```

2018-09-17 20:23 UTC, austris-argalis commented
Hey, @naydav 
I re-run tests after rebasing on the latest code from 2.3-dev branch and everything was still green.

Is there something specific about the env this output is from that could help me with debugging?
I see the actual error is 
> Internal server error

but don't know how to reproduce such conditions.

2018-09-18 16:55 UTC, naydav commented
@austris-argalis
Looks like these tests are failed on Magento internal builds
I am going to recheck them

2018-09-20 02:30 UTC, merged