Mutations coupons
magento/graphql-ce pull request #163
Opened 2018-08-30 12:10 UTC by rogyar

### Description
The PR introduces logic for working with shopping cart coupons. It adds two operations `applyCouponToCart` and `removeCouponFromCart`. 
Also, within a scope of this PR an additional interface for checking cart operations permissions is added. By using this class we can restrict a customer cart from editing by a guest or another customer. 

### Fixed Issues (if relevant)

1. https://github.com/magento/graphql-ce/issues/64: [Mutations] Cart Operations > Coupons

### Manual testing scenarios
- Create a coupon in the system that is applicable for all products.
- Create a shopping cart (quote) with items
- Use the cart masked id for performing the applyCouponToCart and removeCouponFromCart correspondingly

**Apply coupon**
```
mutation {
  applyCouponToCart(input: {cart_id: "6324c290f30fc195f812de670705efd1", coupon_code: "test"}) {
    cart {
      applied_coupon {
        code
      }
    }
  }
}

```

**Remove coupon**
```
mutation {
  removeCouponFromCart(input: {cart_id: "6324c290f30fc195f812de670705efd1"}) {
    cart {
      applied_coupon {
        code
      }
    }
  }
}

```

2018-08-31 23:41 UTC, paliarush commented on app/code/Magento/QuoteGraphQl/Model/CartMutationsAllowed.php
> +        if (!$customerId) {
Please add comments to explain allowed use cases. It might be not obvious why we have this checks.

2018-08-31 23:48 UTC, paliarush commented on app/code/Magento/QuoteGraphQl/Model/CartMutationsAllowedInterface.php
> +interface CartMutationsAllowedInterface
All classes/interfaces should be named using nouns. Please consider making changes across the review. In this specific case something like `Authorization\CartMutation::isAllowed` sounds better

2018-09-01 03:35 UTC, paliarush commented on app/code/Magento/QuoteGraphQl/Model/Resolver/Coupon/ApplyCouponToCart.php
> +            throw new GraphQlInputException(__('Required parameter is missing'));
It is better to specify which parameter is missing (have two separate exceptions)

2018-09-01 03:37 UTC, paliarush commented on app/code/Magento/QuoteGraphQl/Model/Resolver/Coupon/ApplyCouponToCart.php
> +                __('Operations with selected cart is not permitted for current user')
'cart is not permitted' => 'cart are not permitted'

2018-09-01 03:50 UTC, paliarush commented on app/code/Magento/QuoteGraphQl/Model/Resolver/Coupon/ApplyCouponToCart.php
> +            throw new GraphQlInputException(__($exception->getMessage()));
We must not display exception messages from `\Exception` to the clients, they may contain sensitive information. Please log the original exception message and display some generic one.

Please make sure to fix similar issues across the PR if any.

2018-09-01 04:07 UTC, paliarush commented on app/code/Magento/QuoteGraphQl/Model/Resolver/Coupon/ApplyCouponToCart.php
> +        $result = function () use ($data) {
How is it possible to get the full cart object if needed?

2018-09-01 04:13 UTC, paliarush commented on app/code/Magento/QuoteGraphQl/README.md
> +**QuoteGraphQl** provides type and resolver information for the GraphQl module
In GraphQL we should not use word `endpoint`, instead we have queries and mutations

2018-09-01 04:20 UTC, paliarush commented on app/code/Magento/QuoteGraphQl/etc/schema.graphqls
> +    # Wrapper allows for future extension of coupon info
We probably don't need to leave such comments in the schema.

2018-09-01 04:20 UTC, keharper commented on app/code/Magento/QuoteGraphQl/Model/Resolver/Coupon/ApplyCouponToCart.php
> +            throw new GraphQlNoSuchEntityException(__('No cart with provided ID found'));
If you can include the ID, then change the exception text to

'Could not find a cart with ID <ID_number>'

Otherwise, change exception text to 'Could not find a cart with the provided ID'

2018-09-01 04:20 UTC, keharper commented on app/code/Magento/QuoteGraphQl/Model/Resolver/Coupon/ApplyCouponToCart.php
> +                __('Operations with selected cart is not permitted for current user')
If you can include the cart ID, change exception text to 
'The current user cannot perform operations on cart <cart_id>'

Otherwise, change the text to 
The current user cannot perform operations on the selected cart'

2018-09-01 04:20 UTC, keharper commented on app/code/Magento/QuoteGraphQl/Model/Resolver/Coupon/RemoveCouponFromCart.php
> +        if (!$maskedCartId) {
Apply the same edits to the exception text as with `ApplyCouponToCart.php`

2018-09-01 04:20 UTC, keharper commented on app/code/Magento/QuoteGraphQl/README.md
> +to generate quote (cart) information endpoints. Also provides endpoints for modifying a quote.
Change second sentence to 

It also provides...

2018-09-01 04:20 UTC, keharper commented on app/code/Magento/QuoteGraphQl/etc/schema.graphqls
> +    createEmptyCart: String @resolver(class: "\\Magento\\QuoteGraphQl\\Model\\Resolver\\Cart\\CreateEmptyCart") @doc(description:"Creates empty shopping cart for guest or logged in user")
Change description to

Creates an empty shopping cart for a guest or a logged in user

2018-09-01 04:21 UTC, paliarush commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/CouponTest.php
> + * Test for empty cart creation mutation
Please fix the comment

2018-09-01 04:24 UTC, paliarush requested changes
Great contribution! Please address several minor comments and we should be good to merge.

2018-09-18 16:28 UTC, paliarush commented on app/code/Magento/QuoteGraphQl/Model/Resolver/Coupon/ApplyCouponToCart.php
> +     * @var IsCartMutationAllowedForCurrentUser
Should be `@var bool`. Please fix in other places in current PR

2018-09-18 16:30 UTC, paliarush approved these changes

2018-09-20 02:30 UTC, merged