139: Show only active categories
magento/graphql-ce pull request #164
Opened 2018-08-31 10:00 UTC by nuzil

### Description

We fixed this issue with this PR
https://app.zenhub.com/workspace/o/magento/graphql-ce/issues/139
https://app.zenhub.com/workspace/o/magento/graphql-ce/issues/246

So currently only Active categories will be delivered with request

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-08-31 10:00 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=164) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=164) before we can accept your contribution.<br/>

2018-08-31 22:41 UTC, paliarush approved these changes
Would be perfect if we can cover this with tests.

2018-09-13 11:06 UTC, naydav commented
Pls check
```
Magento\GraphQl\Catalog\CategoryTest::testCategoriesTree
Failed asserting that null matches expected 'Ololo'.

/opt/bamboo/builds/MCCE23-AT1226-SOE/build-1/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/CategoryTest.php:87
```

2018-09-20 12:30 UTC, andrewizotov commented
> Pls check
> 
> ```
> Magento\GraphQl\Catalog\CategoryTest::testCategoriesTree
> Failed asserting that null matches expected 'Ololo'.
> 
> /opt/bamboo/builds/MCCE23-AT1226-SOE/build-1/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/CategoryTest.php:87
> ```
Hello Valeriy , I tested default behaviour on develop branch  your test case. 
And I see some problems around child categories . please have a look . 
this is your categories tree . 
![g1](https://user-images.githubusercontent.com/17500052/45817898-c9455980-bce8-11e8-89be-cb4a8686ca57.PNG)
and answer 
`
{
  "data": {
    "category": {
      "id": 2,
      "name": "Default Category",
      "level": 1,
      "description": null,
      "path": "1/2",
      "path_in_store": null,
      "product_count": 1182,
      "url_key": "default-category",
      "url_path": null,
      "children": [
        {
          "id": 3,
          "name": "Category 1",
          "description": null,
          "available_sort_by": [],
          "default_sort_by": "name",
          "image": null,
          "level": 2,
          "children": []
        },
        {
          "id": 6,
          "name": "Category 2",
          "description": null,
          "available_sort_by": [],
          "default_sort_by": "name",
          "image": null,
          "level": 2,
          "children": []
        },
        {
          "id": 7,
          "name": "Movable",
          "description": null,
          "available_sort_by": [],
          "default_sort_by": "name",
          "image": null,
          "level": 2,
          "children": []
        },
        {
          "id": 8,
          "name": "Inactive",
          "description": null,
          "available_sort_by": [],
          "default_sort_by": "name",
          "image": null,
          "level": 2,
          "children": []
        },
        {
          "id": 9,
          "name": "Movable Position 1",
          "description": null,
          "available_sort_by": [],
          "default_sort_by": "name",
          "image": null,
          "level": 2,
          "children": []
        },
        {
          "id": 10,
          "name": "Movable Position 2",
          "description": null,
          "available_sort_by": [],
          "default_sort_by": "name",
          "image": null,
          "level": 2,
          "children": []
        },
        {
          "id": 11,
          "name": "Movable Position 3",
          "description": null,
          "available_sort_by": [],
          "default_sort_by": "name",
          "image": null,
          "level": 2,
          "children": []
        },
        {
          "id": 12,
          "name": "Category 12",
          "description": null,
          "available_sort_by": [],
          "default_sort_by": "name",
          "image": null,
          "level": 2,
          "children": [
            {
              "id": 4,
              "name": "Category 1.1",
              "filter_price_range": null,
              "description": null,
              "image": null,
              "meta_keywords": null,
              "level": 3,
              "is_anchor": 1,
              "children": []
            },
            {
              "id": 13,
              "name": "Category 1.2",
              "filter_price_range": null,
              "description": "Ololo",
              "image": null,
              "meta_keywords": null,
              "level": 3,
              "is_anchor": 1,
              "children": [
                {
                  "name": "Category 1.1.1",
                  "level": 4,
                  "id": 5
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
`

2018-10-11 14:33 UTC, paliarush commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php
> -    private function processTree(\Iterator $iterator) : array
Why is this code not necessary anymore?

2018-10-15 08:23 UTC, nuzil commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php
> -    private function processTree(\Iterator $iterator) : array
I guess it was mergin with 2.3-develop, cause currently I dont see processTree in https://github.com/magento/graphql-ce/blob/2.3-develop/app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php

2018-10-23 22:17 UTC, paliarush reviewed
This is pretty complex change, please make sure to cover it with GraphQL test.

2018-10-23 22:17 UTC, paliarush commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/ExtractDataFromCategoryTree.php
> +     * Merge together complex categories tree
How about `categories tree` => `category trees` ?
Same regarding method name itself.

2018-10-23 22:17 UTC, paliarush commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/ExtractDataFromCategoryTree.php
> +    private function generateLevelTree($elements, $index): array
Method name is not reflecting its purpose, need to read the docs to understand what it is doing. Please consider improving method name.

2018-11-08 14:23 UTC, nuzil commented
@paliarush Tests are there and aligned, just pushed last update

2018-11-08 16:01 UTC, paliarush approved these changes

2018-11-13 13:01 UTC, naydav requested changes

2018-11-13 13:01 UTC, naydav commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/ExtractDataFromCategoryTree.php
> +            $currentLevelTree = $this->explodePathToArray($pathElements, self::START_CATEGORY_FETCH_LEVEL);
@paliarush @nuzil 
This changes will be broke current logic

Query:
```
{
  category(id: 334) {
   id
    name
  }
}
```

The result before changes:
```
{
  "data": {
    "category": {
      "id": 334,
      "name": "Cat-1"
    }
  }
}
```

The result after changes:
```
{
  "data": {
    "category": {
      "id": 2,
      "name": null
    }
  }
}
```
The root category has always been loaded first.

Looks like we need to change 
```
const START_CATEGORY_FETCH_LEVEL = 1;
```
on
```
const START_CATEGORY_FETCH_LEVEL = 2;
```

2018-11-20 17:27 UTC, nuzil commented
Hey @naydav, you was close. reason in different deepness level calculation for each category. I extended code and also added one additional test for this case

2018-11-27 07:51 UTC, raivisdejus commented
@nuzil From the quick glance this fix is still missing sorting by the position. If you re-arrange the categories the tree in GraphQl will not match without this filter. That is implemented here https://github.com/magento/graphql-ce/pull/257/files#diff-b63924c5648c0a0b6c687d44f7bb7db3R105

@naydav  and @paliarush I think my solution for the ExtractDataFromCategoryTree.php is simpler and it also has unit tests to cover the basics of the implementation.

2018-11-28 10:41 UTC, nuzil commented
@magento-engcom-team give me test instance

2018-12-17 17:33 UTC, paliarush approved these changes

2018-12-18 12:52 UTC, naydav commented
We have static tests fail
1)
```
Magento\Test\Php\LiveCodeTest::testCodeMess
PHP Code Mess has found error(s):
/var/www/html/app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php:24	The class CategoryTree has a coupling between objects value of 13. Consider to reduce the number of dependencies under 13.
```
2)
```
FILE: ...l/Resolver/Products/DataProvider/ExtractDataFromCategoryTree.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 57 | ERROR | [x] Expected 1 space(s) after closing parenthesis;
    |       |     found 0
```

2018-12-19 15:58 UTC, nuzil commented
Hi @naydav , I fixed test and removed dependency, let me know if there are some other changes required

2019-01-24 08:38 UTC, merged