GraphQL-129: Retrieve Customer token
magento/graphql-ce pull request #180
Opened 2018-09-11 22:59 UTC by pfantini

### Description
Create new mutation to retrive customer token by email and password

### Manual testing scenarios

1. Run the following request in GraphiQL:
```
mutation {
   generateCustomerToken(
      email: "customer@example.com"
      password: "password"
   )
}
```

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-09-11 22:59 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=180) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=180) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: pfantini<br/>:x: chrom

2018-09-13 11:19 UTC, naydav requested changes

2018-09-13 11:19 UTC, naydav commented on app/code/Magento/CustomerGraphQl/Model/Resolver/Customer/Account/GenerateCustomerToken.php
> +class GenerateCustomerToken implements ResolverInterface
Pls, provide dockblock for class

2018-09-13 11:19 UTC, naydav commented on app/code/Magento/CustomerGraphQl/Model/Resolver/Customer/Account/GenerateCustomerToken.php
> +
Extra line

2018-09-13 11:19 UTC, naydav commented on app/code/Magento/CustomerGraphQl/Model/Resolver/Customer/Account/GenerateCustomerToken.php
> +    ): Value {
Pls, merge mainline
`Magento\Framework\GraphQl\Query\ResolverInterface` was  changed
In this case we need to return `string` value

2018-09-13 11:19 UTC, naydav commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Customer/GenerateCustomerTokenTest.php
> +
Extra line

2018-09-13 12:09 UTC, magento-engcom-team commented
@pfantini thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-09-13 13:54 UTC, TomashKhamlai commented on app/code/Magento/CustomerGraphQl/Model/Resolver/Customer/Account/GenerateCustomerToken.php
> +                return !empty($token) ? $token : '';
Please change to
return !empty($token) ? ['token' => $token] : '';

or `Cannot return null for non-nullable field GenerateCustomerTokenOutput.token.` error will appear

2018-09-13 13:55 UTC, TomashKhamlai commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Customer/GenerateCustomerTokenTest.php
> +    )
Please add `token` to subselection.

2018-09-13 13:55 UTC, TomashKhamlai commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Customer/GenerateCustomerTokenTest.php
> +    )
Please add `token` to subselection.

2018-09-13 13:56 UTC, TomashKhamlai commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Customer/GenerateCustomerTokenTest.php
> +        $this->assertInternalType('string', $response['generateCustomerToken']);
Please change 'string' to 'array'

2018-09-14 03:49 UTC, pfantini commented on app/code/Magento/CustomerGraphQl/Model/Resolver/Customer/Account/GenerateCustomerToken.php
> +    ): Value {
If I change returned value to string or array the test `Magento\GraphQl\IntrospectionQueryTest::testIntrospectionQueryWithFieldArgs` fails

2018-09-18 23:23 UTC, merged