GraphQl shipping address coverage
magento/graphql-ce pull request #192
Opened 2018-09-22 15:20 UTC by VitaliyBoyko

### Description
Added concept for shipping address coverage

2018-11-02 10:49 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=192) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=192) before we can accept your contribution.<br/>**3** out of **13** committers have signed the CLA.<br/><br/>:white_check_mark: TomashKhamlai<br/>:white_check_mark: dmytro-ch<br/>:white_check_mark: rogyar<br/>:x: joanhe<br/>:x: pmclain<br/>:x: StrikerRUS<br/>:x: gy741<br/>:x: mage2pratik<br/>:x: magento-engcom-team<br/>:x: davemacaulay<br/>:x: Alexey Yakimovich<br/>:x: dthampy<br/>:x: omiroshnichenko<hr/>**Alexey Yakimovich** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2018-11-06 22:09 UTC, keharper requested changes

2018-11-06 22:09 UTC, keharper commented on app/code/Magento/QuoteGraphQl/Model/Cart/SetShippingAddressOnCart.php
> +                __('Multiple addresses do not allowed here!')
Change exception text to 

You cannot specify multiple shipping addresses.

2018-11-06 22:09 UTC, keharper commented on app/code/Magento/QuoteGraphQl/Model/Cart/SetShippingAddressOnCart.php
> +                __('Shipping address should contain either "customer_address_id" or "address" input.')
Change exception text to

The shipping address must contain either "customer_address_id" or "address".

2018-11-06 22:09 UTC, keharper commented on app/code/Magento/QuoteGraphQl/Model/Cart/SetShippingAddressOnCart.php
> +                __('Shipping address can\'t contain "customer_address_id" and "address" input at the same time.')
Change exception text to 

The shipping address cannot contain "customer_address_id" and "address" at the same time.

2018-11-06 22:09 UTC, keharper commented on app/code/Magento/QuoteGraphQl/Model/Cart/SetShippingAddressOnCart.php
> +                        'Address management allowed only for authorized customers.'
Change exception text to

Guest users cannot manage addresses.

2018-11-06 22:09 UTC, keharper commented on app/code/Magento/QuoteGraphQl/Model/Cart/SetShippingAddressesOnCartInterface.php
> + * All objects that are responsible for set shipping addresses on cart via GraphQl should implement this interface.
Change "set" to "setting" and insert "a" between "on" and "cart"

2018-11-06 22:09 UTC, keharper commented on app/code/Magento/QuoteGraphQl/etc/schema.graphqls
> +    createEmptyCart: String @resolver(class: "\\Magento\\QuoteGraphQl\\Model\\Resolver\\Cart\\CreateEmptyCart") @doc(description:"Creates empty shopping cart for guest or logged in user")
Change description to

Creates an empty shopping cart for a guest or logged in user

2018-11-07 18:36 UTC, VitaliyBoyko commented
Hi @keharper 
Thank you for review.
I've fixed all the issues you've mentioned.
Please check :)

2018-11-07 19:06 UTC, keharper approved these changes

2018-11-19 19:28 UTC, merged