160 - Add Revoke Customer token
magento/graphql-ce pull request #195
Opened 2018-09-27 16:52 UTC by ArturoI

### Description
#160 
 - Create mutation to revoke customer token
 - Create functional test.

### Manual testing scenarios
1)  Loggin into the storefront or add the authorization header
2) Run the following request in GraphQL to revoke customer token 
`  mutation {
                revokeCustomerToken
            }`
3) customer token should be deleted

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-09-27 16:52 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=195) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=195) before we can accept your contribution.<br/>

2018-10-01 09:19 UTC, naydav requested changes

2018-10-01 09:19 UTC, naydav commented on app/code/Magento/CustomerGraphQl/Model/Resolver/Customer/Account/RevokeCustomerToken.php
> +        return $this->valueFactory->create($result);
Pls, remove return `Value`. It's need only for deferred cases. In our case, we can return result of ` $this->customerTokenService->revokeCustomerAccessToken($customerId);`
See updated `ResolverInterface`

2018-10-02 16:32 UTC, magento-engcom-team commented
@ArturoI thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2018-10-04 10:56 UTC, merged