Products: Access to related up sell cross sell product fields
magento/graphql-ce pull request #249
Opened 2018-11-15 13:50 UTC by VoronoyAlexandr

### Description (*)
PR For issue #198 Products: access to related/up-sell/cross-sell product fields
This PR added functionality for query/response with related products.

### Manual testing scenarios (*)
Sample request
```
{
  products(filter: { sku: { eq: "product_dynamic_8" } }) {
    items {
      id
      name
      url_key
      categories {
        id
      }
      crosssell_products {
        items {
          name
          sku
          url_key
          canonical_url
          image {
            url
          }
          price {
            regularPrice {
              amount {
                value
              }
            }
            minimalPrice {
              amount {
                value
              }
            }
            maximalPrice {
              amount {
                value
              }
            }
          }
        }
      }
      upsell_products {
        items {
          name
          sku
          url_key
          canonical_url
          image {
            url
          }
          price {
            regularPrice {
              amount {
                value
              }
            }
            minimalPrice {
              amount {
                value
              }
            }
            maximalPrice {
              amount {
                value
              }
            }
          }
        }
      }
      related_products {
        items {
          name
          sku
          url_key
          canonical_url
          image {
            url
            label
          }
          price {
            regularPrice {
              amount {
                value
                currency
              }
              adjustments {
                amount {
                  value
                  currency
                }
                code
                description
              }
            }
            maximalPrice {
              amount {
                value
                currency
              }
              adjustments {
                amount {
                  value
                  currency
                }
                code
                description
              }
            }
            minimalPrice {
              amount {
                value
                currency
              }
              adjustments {
                amount {
                  value
                  currency
                }
                code
                description
              }
            }
          }
        }
      }
    }
  }
}

```
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-03 15:04 UTC, naydav requested changes

2018-12-03 15:04 UTC, naydav commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Product/Related/CrossSellProducts.php
> +    public const FIELDS = ['sku', 'name', 'price', 'image', 'url_path', 'url_key'];
We should take this data from request

2018-12-03 15:04 UTC, naydav commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Product/Related.php
> +<?php
Pls, add `declare(strict_types=1);` to all of new files
And check code style of all of files

2018-12-03 15:04 UTC, naydav commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Product/Related/CrossSellProducts.php
> +    public function resolve(Field $field, $context, ResolveInfo $info, array $value = null, array $args = null)
We can use `inheritdoc`

2018-12-03 15:04 UTC, naydav commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Product/Related/RelatedProducts.php
> +        foreach ($collection as $item) {
`foreach ($data as $key => $value)`

2018-12-03 15:04 UTC, naydav commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/Related/AbstractDataProvider.php
> +abstract class AbstractDataProvider
Pls, don't use supertypes only for code reusing (if a relation is not like `type A is subtype of B`)

2018-12-03 15:04 UTC, naydav commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/Related/CrossSellDataProvider.php
> +        $this->collection = $product->getCrossSellProductCollection();
Looks like proxy on another method

2018-12-03 15:04 UTC, naydav commented on app/code/Magento/CatalogGraphQl/etc/schema.graphqls
> +    related_products: RelatedProduct @doc(description: "RelatedProduct") @resolver(class: "Magento\\CatalogGraphQl\\Model\\Resolver\\Product\\Related")
Looks like resolver should be `Magento\\CatalogGraphQl\\Model\\Resolver\\Product\\Related\\RelatedProducts`
Why do we need one more layer?
The same for another types of related products

2019-01-23 21:26 UTC, naydav commented
Hello @VoronoyAlexandr,
We still need some changes to finish the PR, will you continue progress? 
Thank you

Please let me know if you need any assistance.

2019-02-13 08:40 UTC, VitaliyBoyko commented
Closing due to inactivity.

2019-02-13 08:40 UTC, closed without merging