Added label from store view
magento/graphql-ce pull request #252
Opened 2018-11-17 16:39 UTC by VoronoyAlexandr

### Description (*)
PR for issue #250 Configurable Options Label doesn't return the Store View Label
This PR added functionality to show store label in label response

### Fixed Issues (if relevant)

magento/graphql-ce#250: Configurable Options Label doesn't return the Store View Label

### Manual testing scenarios (*)
Request: Store Label "Custom Color", Default label "Color"
```
{
  products(filter: { sku: { eq: "Test Configurable" } }) {
    items {
      name
      ... on ConfigurableProduct {
        configurable_options {
          attribute_code
          id
          label
        }
      }
    }
  }
}
```
Response:
```
{
  "data": {
    "products": {
      "items": [
        {
          "name": "Test Configurable",
          "configurable_options": [
            {
              "attribute_code": "color",
              "id": 35,
              "label": "Custom Color"
            }
          ]
        }
      ]
    }
  }
}
```

Response with empty Store Label
```
{
  "data": {
    "products": {
      "items": [
        {
          "name": "Test Configurable",
          "configurable_options": [
            {
              "attribute_code": "color",
              "id": 35,
              "label": "Color"
            }
          ]
        }
      ]
    }
  }
}
```
Also tested with different store and with branch 2.3-develop.
Api-functional test included.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-03 14:08 UTC, naydav requested changes

2018-12-03 14:08 UTC, naydav commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Swatches/ProductViewTest.php
> +class ProductViewTest extends GraphQlAbstract
Rename test in a more clear way like `GetSwatchDataTest`

2018-12-03 14:08 UTC, naydav commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Swatches/ProductViewTest.php
> +    private $configurableOptions = [];
Why do we need `state` in the test?

2018-12-03 14:08 UTC, naydav commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Swatches/ProductViewTest.php
> +     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
Looks like is redundant `SuppressWarnings`

2018-12-03 14:08 UTC, naydav commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Swatches/ProductViewTest.php
> +        $productRepository = ObjectManager::getInstance()->get(ProductRepositoryInterface::class);
Pls, move all of the initialization in `setUp`

2018-12-03 14:08 UTC, naydav commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Swatches/ProductViewTest.php
> +        $product->setId(
Why do we need set something to the loaded product? We need to emulate client code

2018-12-03 14:08 UTC, naydav commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Swatches/ProductViewTest.php
> +            foreach ($optionData['options'] as $data) {
Why do we need ane more `foreach`?
We can put in assertEquals two arrays

2018-12-03 14:08 UTC, naydav commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Swatches/ProductViewTest.php
> +            $cnt = 0;
Syntaxis of `foreach` operator  is `foreach ($data as $key => $value)`
So we don't need aditional variable `$cnt`

2018-12-03 14:08 UTC, naydav commented on dev/tests/integration/testsuite/Magento/Swatches/_files/swatch_attribute_color.php
> +$objectManager = \Magento\TestFramework\Helper\Bootstrap::getObjectManager();
Why do we need this fixture if we already have `dev/tests/integration/testsuite/Magento/Swatches/_files/swatch_attribute.php`?

2018-12-03 14:08 UTC, naydav commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Swatches/ProductViewTest.php
> +        $this->assertResponseFields($actualResponse, $assertionMap);
Looks like we can use a few simple `assertEquals` instead of complex `assertResponseFields`

2019-01-23 21:27 UTC, naydav commented
Hello @VoronoyAlexandr,
We still need some changes to finish the PR, will you continue progress? 
Thank you

Please let me know if you need any assistance.

2019-01-30 11:47 UTC, VitaliyBoyko commented
No progress here.
Closing this one.
@sergiy-v gonna proceed with the task.

2019-01-30 11:47 UTC, closed without merging