GraphQl-93: Implement support for variables in query
magento/graphql-ce pull request #259
Opened 2018-11-20 17:54 UTC by Aquarvin

-- Variables may be Input type
-- Query now accepts variables
-- added type property for Output/Input Type element
-- functional test was added

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-11-20 18:02 UTC, Aquarvin commented
Request Sample:
```
query GetProductsQuery($page: Int, $filterInput: ProductFilterInput){
  products(
    pageSize: 10
    currentPage: $page
    filter: $filterInput
    sort: {}
  ) {
    items {
    	name
    }
  }
}
```
With variables:

> {
>   "page": 1,
>   "filterInput": {
>     "price": {
>     	"gt": "10"
>     }
>   }
> }

2018-12-12 15:43 UTC, paliarush approved these changes

2019-01-17 23:57 UTC, paliarush requested changes

2019-01-17 23:57 UTC, paliarush commented on dev/tests/api-functional/testsuite/Magento/GraphQl/VariablesSupportQueryTest.php
> +query GetProductsQuery($page: Int, $filterInput: ProductFilterInput){
Do we have enum used here?

2019-01-17 23:57 UTC, paliarush commented on lib/internal/Magento/Framework/GraphQl/Config.php
> +     *  name string
Is this common style for documenting array structure? Usually I see 
`['name' => 'example value', 'type' = 'example value']`

2019-01-17 23:57 UTC, paliarush commented on lib/internal/Magento/Framework/GraphQl/Config.php
>      public function getDeclaredTypeNames() : array
Can we rename this method, to `getDeclaredTypes`, for example

2019-01-17 23:57 UTC, paliarush commented on lib/internal/Magento/Framework/GraphQl/Config/Element/InputFactory.php
> +     * Create type object based off array of configured GraphQL InputType data.
```suggestion
     * Create input type object based off array of configured GraphQL InputType data.
```

2019-01-17 23:57 UTC, paliarush commented on lib/internal/Magento/Framework/GraphQl/Config/Element/Type.php
> + * Class representing 'type' GraphQL config element.
```suggestion
 * Class representing 'type' GraphQL config elements.
```

2019-01-17 23:57 UTC, paliarush commented on lib/internal/Magento/Framework/GraphQl/Query/Fields.php
> +    private function getVariables(array $variables): array
```suggestion
    private function formatVariables(array $variables): array
```
or maybe `extractVariables`

2019-01-17 23:57 UTC, paliarush commented on lib/internal/Magento/Framework/GraphQl/Schema/SchemaGenerator.php
> +                    foreach ($this->config->getDeclaredTypeNames() as $type) {
Please create a ticket not to load all types, but just the ones which do not have references from Query/Mutation types

2019-01-17 23:57 UTC, paliarush commented on lib/internal/Magento/Framework/GraphQl/Schema/Type/TypeRegistry.php
> +                    new Phrase("Type for '{$configElementClass}' has not declared.")
```suggestion
                    new Phrase("No mapping to Webonyx type is declared for '{$configElementClass}' config element type.")
```

2019-01-22 21:30 UTC, magento-engcom-team commented
@Aquarvin thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-01-23 23:45 UTC, merged

2019-01-24 14:02 UTC, danslo commented
I'm not sure if this fixes every case. For example, I try with this query:

```
query testQuery($sort: ProductSortInput) {
  products(sort: $sort) {
    items {
      name
    }
  }
}
```

With query variables:
```
{
  "sort": {
    "name":"ASC"
  }
}
```

Getting these errors:
- "Variable \"$sort\" cannot be non-input type \"ProductSortInput\".",
- "Variable \"$sort\" of type \"ProductSortInput\" used in position expecting type \"ProductSortInput\".",