Fixed variant collection
magento/graphql-ce pull request #265
Opened 2018-11-24 22:18 UTC by VoronoyAlexandr

### Description (*)
This PR fixed empty response for variant in ConfigurableProduct with sample data.

### Fixed Issues (if relevant)
1. magento/magento2#256: Configurable products > Variants > Attributes are empty

### Manual testing scenarios (*)
Request
```
{
  products(filter: {sku: {eq: "WP13"}}) {
    items {
      name
      ... on ConfigurableProduct {
        sku
        variants {
          product {
            sku
          }
          attributes {
            label
            code
            value_index
          }
        }
      }
    }
  }
}
```
Response
```
{
  "data": {
    "products": {
      "items": [
        {
          "name": "Portia Capri",
          "sku": "WP13",
          "variants": [
            {
              "product": {
                "sku": "WP13-28-Blue"
              },
              "attributes": [
                {
                  "label": "Blue",
                  "code": "color",
                  "value_index": 50
                },
                {
                  "label": "28",
                  "code": "size",
                  "value_index": 172
                }
              ]
            },
            {
              "product": {
                "sku": "WP13-28-Green"
              },
              "attributes": [
                {
                  "label": "Green",
                  "code": "color",
                  "value_index": 53
                },
                {
                  "label": "28",
                  "code": "size",
                  "value_index": 172
                }
              ]
            },
            {
              "product": {
                "sku": "WP13-28-Orange"
              },
              "attributes": [
                {
                  "label": "Orange",
                  "code": "color",
                  "value_index": 56
                },
                {
                  "label": "28",
                  "code": "size",
                  "value_index": 172
                }
              ]
            },
            {
              "product": {
                "sku": "WP13-29-Blue"
              },
              "attributes": [
                {
                  "label": "Blue",
                  "code": "color",
                  "value_index": 50
                },
                {
                  "label": "29",
                  "code": "size",
                  "value_index": 173
                }
              ]
            },
            {
              "product": {
                "sku": "WP13-29-Green"
              },
              "attributes": [
                {
                  "label": "Green",
                  "code": "color",
                  "value_index": 53
                },
                {
                  "label": "29",
                  "code": "size",
                  "value_index": 173
                }
              ]
            },
            {
              "product": {
                "sku": "WP13-29-Orange"
              },
              "attributes": [
                {
                  "label": "Orange",
                  "code": "color",
                  "value_index": 56
                },
                {
                  "label": "29",
                  "code": "size",
                  "value_index": 173
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
```
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-03 14:36 UTC, naydav requested changes

2018-12-03 14:36 UTC, naydav commented on app/code/Magento/ConfigurableProductGraphQl/Model/Variant/Collection.php
> +        if (!in_array($product, $this->parentProduct) && !empty($this->childrenMap)) {
You should not use objects for `in_array` but you can use structure like key is product id, value is object

2018-12-03 14:36 UTC, naydav commented on app/code/Magento/ConfigurableProductGraphQl/Model/Variant/Collection.php
> +    private function getAttributesCode(Product $currentProduct): array
Looks like we can use more simple way for loading all of the possible (visible) attribute codes instead of loading attributes models

2019-01-23 21:29 UTC, naydav commented
Hello @VoronoyAlexandr,
We still need some changes to finish the PR, will you continue progress? 
Thank you

Please let me know if you need any assistance.

2019-01-29 18:19 UTC, VitaliyBoyko commented
No progress here.
Closing this one.

2019-01-29 18:19 UTC, closed without merging