Add endpoint for fetching/deleting vault tokens
magento/graphql-ce pull request #307
Opened 2018-12-27 13:41 UTC by pmclain

### Description (*)
Add query for fetching visible payment tokens:
```graphql
customerPaymentTokens {
     items {
        public_hash
        details
        payment_method_code
        type
    }
}
```
The `details` property is the string value of `vault_payment_token.details`. This field contains serialized details that vary by the payment implementation. I'm not sure if we want to expose an interface for formatting this information similar to what is used in Magento_InstantPurchase or leave as-is.

Add mutation for deleting payment tokens:
```graphql
deletePaymentToken (
    public_hash: {{someHash}}
) {
    result
}
```

### Fixed Issues (if relevant)
1. magento/graphql-ce#46: [Query] My Account > Stored Payment Methods

### Manual testing scenarios (*)
1. Configure payment method supporting vault and enable
2. Checkout via storefront or admin using payment method and select option to save for later
3. Use query above to retrieve stored payment tokens via graphql **requires authentication**
4. Use mutation above to delete stored payment token via graphql **requires authentication**
5. Use query above to validate deleted payment token is no longer returned via graphql **requires authentication**

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-08 17:29 UTC, paliarush requested changes

2019-01-08 17:29 UTC, paliarush commented on app/code/Magento/VaultGraphQl/Model/PaymentTokenManagement.php
> +class PaymentTokenManagement
How about `VisibleTokenRetriever` or something similar? 
`*Management` should be avoided in class names as too generic.

2019-01-08 17:29 UTC, paliarush commented on app/code/Magento/VaultGraphQl/Model/Resolver/DeletePaymentToken.php
> + * Payment Token resolver, used for GraphQL request processing.
Please update description

2019-01-08 17:29 UTC, paliarush commented on app/code/Magento/VaultGraphQl/README.md
> +provides endpoints for modifying a payment token.
```suggestion
provides mutations for modifying a payment token.
```

2019-01-08 17:29 UTC, paliarush commented on app/code/Magento/VaultGraphQl/composer.json
> +        "magento/module-graph-ql": "*"
It is interesting, will it even work without GraphQL module?

2019-01-08 17:29 UTC, paliarush commented on app/code/Magento/VaultGraphQl/etc/schema.graphqls
> +    result: Boolean!
I believe it makes sense to allow retrieval of updated `customerPaymentTokens` value as a result of mutation to prevent subsequent query when rendering the list again.

How about having two fields here:
```
result: Bolean!
customerPaymentTokens: CustomerPaymentTokens
```

2019-01-08 17:29 UTC, paliarush commented on app/code/Magento/VaultGraphQl/etc/schema.graphqls
> +    items: [PaymentToken] @doc(description: "An array of payment tokens")
```suggestion
    items: [PaymentToken]! @doc(description: "An array of payment tokens")
```
I assume at least an empty array will always be returned.

2019-01-08 17:29 UTC, paliarush commented on app/code/Magento/VaultGraphQl/etc/schema.graphqls
> +    type: String! @doc(description: "Token type [card|account]")
It can be declared as enum if just two values are possible.

2019-01-08 17:29 UTC, paliarush commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Vault/CustomerPaymentTokensTest.php
> +        $this->assertEquals(1, count($response['customerPaymentTokens']['items']));
Ideally, we should validate each field

2019-01-08 18:46 UTC, pmclain commented on app/code/Magento/VaultGraphQl/composer.json
> +        "magento/module-graph-ql": "*"
No. You caught me copying the `composer.json` from another module :)

2019-01-08 18:46 UTC, pmclain commented
@paliarush Thanks for the feedback. The requested changes have been made.

2019-01-08 18:53 UTC, paliarush approved these changes

2019-01-22 17:26 UTC, keharper reviewed
My comments are for descriptions and exception messages.

2019-01-22 17:26 UTC, keharper commented on app/code/Magento/VaultGraphQl/Model/Resolver/DeletePaymentToken.php
> +                __('Token could not be found by public hash: %1', $args['public_hash'])
```suggestion
                __('Could not find a token using public hash: %1', $args['public_hash'])
```

2019-01-22 17:26 UTC, keharper commented on app/code/Magento/VaultGraphQl/README.md
> +to generate Vault (stored payment information) information endpoints. Also
```suggestion
to generate Vault (stored payment information) information endpoints. This module also
```

2019-01-22 17:26 UTC, keharper commented on app/code/Magento/VaultGraphQl/etc/schema.graphqls
> +    deletePaymentToken(public_hash: String!): DeletePaymentTokenOutput @resolver(class: "\\Magento\\VaultGraphQl\\Model\\Resolver\\DeletePaymentToken") @doc(description:"Delete customer Payment Token
```suggestion
    deletePaymentToken(public_hash: String!): DeletePaymentTokenOutput @resolver(class: "\\Magento\\VaultGraphQl\\Model\\Resolver\\DeletePaymentToken") @doc(description:"Delete a customer payment token")
```

2019-01-22 17:26 UTC, keharper commented on app/code/Magento/VaultGraphQl/etc/schema.graphqls
> +    customerPaymentTokens: CustomerPaymentTokens @doc(description: "List of customer payment tokens") @resolver(class: "\\Magento\\VaultGraphQl\\Model\\Resolver\\PaymentTokens")
```suggestion
    customerPaymentTokens: CustomerPaymentTokens @doc(description: "Return a list of customer payment tokens") @resolver(class: "\\Magento\\VaultGraphQl\\Model\\Resolver\\PaymentTokens")
```

2019-01-22 17:26 UTC, keharper commented on app/code/Magento/VaultGraphQl/etc/schema.graphqls
> +    public_hash: String! @doc(description: "Token public hash")
```suggestion
    public_hash: String! @doc(description: "The public hash of the token")
```

2019-01-22 17:26 UTC, keharper commented on app/code/Magento/VaultGraphQl/etc/schema.graphqls
> +type PaymentToken @doc(description: "Stored payment method available to customer") {
```suggestion
type PaymentToken @doc(description: "The stored payment method available to the customer") {
```

2019-01-22 17:26 UTC, keharper commented on app/code/Magento/VaultGraphQl/etc/schema.graphqls
> +    payment_method_code: String! @doc(description: "Payment method code associated with token")
```suggestion
    payment_method_code: String! @doc(description: "The payment method code associated with the token")
```

2019-01-22 18:17 UTC, pmclain commented
@keharper Thanks for review! The suggested changes have been applied.

2019-02-06 21:41 UTC, naydav commented
@pmclain 
Could you fix static tests errors?

1)
```
FILE: ...al/testsuite/Magento/GraphQl/Vault/CustomerPaymentTokensTest.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 155 | ERROR | [x] Function closing brace must go on the next line
     |       |     following the body; found 1 blank lines before
     |       |     brace
```

2)
```
Magento\Test\Php\LiveCodeTest::testCopyPaste
PHP Copy/Paste Detector has found error(s):
<?xml version="1.0" encoding="UTF-8"?>
<pmd-cpd>
  <duplication lines="35" tokens="110">
    <file path="/var/www/html/app/code/Magento/Vault/Model/PaymentTokenManagement.php" line="129"/>
    <file path="/var/www/html/app/code/Magento/VaultGraphQl/Model/VisibleTokenRetriever.php" line="74"/>
    <codefragment>    public function getVisibleAvailableTokens($customerId)
    {
        $customerFilter = [
            $this-&gt;filterBuilder-&gt;setField(PaymentTokenInterface::CUSTOMER_ID)
                -&gt;setValue($customerId)
                -&gt;create()
            ];
        $visibleFilter = [
            $this-&gt;filterBuilder-&gt;setField(PaymentTokenInterface::IS_VISIBLE)
                -&gt;setValue(1)
                -&gt;create()
            ];
        $isActiveFilter = [
            $this-&gt;filterBuilder-&gt;setField(PaymentTokenInterface::IS_ACTIVE)
                -&gt;setValue(1)
                -&gt;create()
            ];
        $expiresAtFilter = [
            $this-&gt;filterBuilder-&gt;setField(PaymentTokenInterface::EXPIRES_AT)
                -&gt;setConditionType('gt')
                -&gt;setValue(
                    $this-&gt;dateTimeFactory-&gt;create(
                        'now',
                        new \DateTimeZone('UTC')
                    )-&gt;format('Y-m-d 00:00:00')
                )
                -&gt;create()
            ];
        $this-&gt;searchCriteriaBuilder-&gt;addFilters($customerFilter);
        $this-&gt;searchCriteriaBuilder-&gt;addFilters($visibleFilter);
        $this-&gt;searchCriteriaBuilder-&gt;addFilters($isActiveFilter);
        // add filters to different filter groups in order to filter by AND expression
        $searchCriteria = $this-&gt;searchCriteriaBuilder-&gt;addFilters($expiresAtFilter)-&gt;create();

        return $this-&gt;paymentTokenRepository-&gt;getList($searchCriteria)-&gt;getItems();
</codefragment>
  </duplication>
</pmd-cpd>
```

2019-02-06 22:38 UTC, pmclain commented
@naydav https://github.com/magento/graphql-ce/pull/307/commits/cc0b1cd7334f8f54f673739494f3542e4a7afca6 should resolve the static tests.

2019-02-14 05:37 UTC, merged