Improve Filter Architecture
magento/graphql-ce pull request #314
Opened 2019-01-08 18:53 UTC by larsroettig

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-08 18:53 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=314) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=314) before we can accept your contribution.<br/>

2019-01-08 19:20 UTC, paliarush requested changes

2019-01-08 19:20 UTC, paliarush commented on lib/internal/Magento/Framework/GraphQl/Query/Resolver/Argument/FieldEntityAttributes.php
> +namespace Magento\Framework\GraphQl\Query\Resolver\Argument;
I think `Filter` should still be part of the namespace because this class is specifically for filterable fields.

2019-01-08 19:20 UTC, paliarush commented on lib/internal/Magento/Framework/GraphQl/Query/Resolver/Argument/FieldEntityAttributes.php
> +        $productTypeSchema = $this->config->getConfigElement($this->configElementName);
Please eliminate all `product` occurrences in this file since now it is generic.

2019-01-08 19:20 UTC, paliarush commented on lib/internal/Magento/Framework/GraphQl/Query/Resolver/Argument/FieldEntityAttributes.php
> +                $fields[$field->getName()] = '';
Why this was changed? I believe each filter value must be of a `String` type. Same below.

2019-01-08 19:20 UTC, paliarush commented on lib/internal/Magento/Framework/GraphQl/Query/Resolver/Argument/FieldEntityAttributes.php
> +    public function getEntityAttributes(): array
For now this method will collect filterable fields from interface declarations and from `additionalAttributes` defined in di.xml, however it does not seem to collect fields from the entity itself.

2019-01-08 19:25 UTC, larsroettig commented on lib/internal/Magento/Framework/GraphQl/Query/Resolver/Argument/FieldEntityAttributes.php
> +                $fields[$field->getName()] = '';
Because currently we use only the array key

2019-01-08 19:25 UTC, larsroettig commented on lib/internal/Magento/Framework/GraphQl/Query/Resolver/Argument/FieldEntityAttributes.php
> +        $productTypeSchema = $this->config->getConfigElement($this->configElementName);
Because currently we use only the array key

2019-01-08 21:04 UTC, paliarush commented on lib/internal/Magento/Framework/GraphQl/Query/Resolver/Argument/Filter/FieldEntityAttributes.php
> +        if ($type->getInterfaces() === null) {
Fields should be read from interfaces AND from the main entity, not OR

2019-03-06 21:39 UTC, naydav commented
Hello @larsroettig,

Unfortunately, we cannot accept this PR because this class is not used anywhere and is not covered by API-functional tests. So it will lead to class obsolescence.

Feel free to reopen with an alternative implementation. It could be an improvement in the current code or it could be some GraphQL scenario described in API-functional tests.

Thanks

2019-03-06 21:39 UTC, closed without merging