[256] Fixed variant collection
magento/graphql-ce pull request #331
Opened 2019-01-29 19:27 UTC by VitaliyBoyko

### Description (*)
This PR fixed empty response for variant in ConfigurableProduct with sample data.

### Fixed Issues (if relevant)
1. magento/graphql-ce#256: Configurable products > Variants > Attributes are empty

### Manual testing scenarios (*)
Request
```
{
  products(filter: {sku: {eq: "WP13"}}) {
    items {
      name
      ... on ConfigurableProduct {
        sku
        variants {
          product {
            sku
          }
          attributes {
            label
            code
            value_index
          }
        }
      }
    }
  }
}
```
Response
```
{
  "data": {
    "products": {
      "items": [
        {
          "name": "Portia Capri",
          "sku": "WP13",
          "variants": [
            {
              "product": {
                "sku": "WP13-28-Blue"
              },
              "attributes": [
                {
                  "label": "Blue",
                  "code": "color",
                  "value_index": 50
                },
                {
                  "label": "28",
                  "code": "size",
                  "value_index": 172
                }
              ]
            },
            {
              "product": {
                "sku": "WP13-28-Green"
              },
              "attributes": [
                {
                  "label": "Green",
                  "code": "color",
                  "value_index": 53
                },
                {
                  "label": "28",
                  "code": "size",
                  "value_index": 172
                }
              ]
            },
            {
              "product": {
                "sku": "WP13-28-Orange"
              },
              "attributes": [
                {
                  "label": "Orange",
                  "code": "color",
                  "value_index": 56
                },
                {
                  "label": "28",
                  "code": "size",
                  "value_index": 172
                }
              ]
            },
            {
              "product": {
                "sku": "WP13-29-Blue"
              },
              "attributes": [
                {
                  "label": "Blue",
                  "code": "color",
                  "value_index": 50
                },
                {
                  "label": "29",
                  "code": "size",
                  "value_index": 173
                }
              ]
            },
            {
              "product": {
                "sku": "WP13-29-Green"
              },
              "attributes": [
                {
                  "label": "Green",
                  "code": "color",
                  "value_index": 53
                },
                {
                  "label": "29",
                  "code": "size",
                  "value_index": 173
                }
              ]
            },
            {
              "product": {
                "sku": "WP13-29-Orange"
              },
              "attributes": [
                {
                  "label": "Orange",
                  "code": "color",
                  "value_index": 56
                },
                {
                  "label": "29",
                  "code": "size",
                  "value_index": 173
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
```
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-29 22:00 UTC, naydav commented
@VitaliyBoyko Looks like we need to cover functionality with API-functional test
Thanks

2019-01-30 12:19 UTC, VitaliyBoyko commented
> @VitaliyBoyko Looks like we need to cover functionality with API-functional test
> Thanks

I've added an additional check if attributes array contains an item.

2019-02-06 19:23 UTC, naydav commented
@VitaliyBoyko 
Pls check
```
Magento.GraphQl.Catalog.CategoryProductsVariantsTest.testGetSimpleProductsFromCategory
Magento.GraphQl.Catalog.CategoryProductsVariantsTest.testGetSimpleProductsFromCategory
Magento.GraphQl.ConfigurableProduct.ConfigurableProductViewTest.testQueryConfigurableProductLinks
Magento.GraphQl.ConfigurableProduct.ConfigurableProductViewTest.testQueryConfigurableProductLinks
```
these tests are faliled on Jenkins
Thanks

2019-02-06 21:47 UTC, naydav requested changes

2019-02-06 21:47 UTC, naydav commented on app/code/Magento/ConfigurableProductGraphQl/Model/Resolver/Variant/Attributes.php
> +            if (!isset($value['product']['model'][$code])) {
Looks like we have a problem at this place because `$value['product']['model']` contains Product model object

2019-02-12 21:22 UTC, merged