Fixed issue #334 Changed hard coded values according to TYPE_CODE
magento/graphql-ce pull request #340
Opened 2019-02-04 14:02 UTC by GovindaSharma

Fixed issue #334 Changed hard coded values according to TYPE_CODE

### Description (*)
Fixed issue #334 Changed hard coded values according to TYPE_CODE

### Fixed Issues (if relevant)

1. magento/magento2 #334: Changed hard coded values according to TYPE_CODE
2. ...

### Manual testing scenarios (*)

   1. Changed hard coded 'Downloadable' to Magento\Downloadable\Model\Product\Type::TYPE_DOWNLOADABLE in
    app/code/Magento/DownloadableGraphQl/Model/DownloadableProductTypeResolver.php

  2.  Changed hard coded 'Bundle' to Magento\Bundle\Model\Product\Type::TYPE_CODE in
    app/code/Magento/BundleGraphQl/Model/BundleProductTypeResolver.php

  3.  Changed hard coded 'Bundle' to Magento\GroupedProduct\Model\Product\Type\Grouped::TYPE_CODE in
    app/code/Magento/GroupedProductGraphQl/Model/GroupedProductTypeResolver.php

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-02-04 14:02 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=340) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=340) before we can accept your contribution.<br/>

2019-02-04 14:49 UTC, nuzil requested changes

2019-02-04 14:49 UTC, nuzil commented on app/code/Magento/BundleGraphQl/Model/BundleProductTypeResolver.php
>              return 'BundleProduct';
Can you please move also this return value to constant?

2019-02-04 14:49 UTC, nuzil commented on app/code/Magento/DownloadableGraphQl/Model/DownloadableProductTypeResolver.php
>              return 'DownloadableProduct';
Can you please move also this return value to constant?

2019-02-04 14:49 UTC, nuzil commented on app/code/Magento/GroupedProductGraphQl/Model/GroupedProductTypeResolver.php
>              return 'GroupedProduct';
Can you please move also this return value to constant?

2019-02-04 15:02 UTC, GovindaSharma commented
hi @nuzil thanks for the update. so should i introduce new constant like COSNT GROUPED_PRODUCT = "GoupedProduct"?

2019-02-04 16:04 UTC, GovindaSharma commented
Hi @nuzil i have updated the code as per your request.Please check it
Thank you

2019-02-05 12:15 UTC, GovindaSharma commented
@nuzil any update on this?

2019-02-12 16:52 UTC, GovindaSharma commented
@nuzil @naydav when this pull request is going to merge?

2019-02-14 23:43 UTC, naydav commented
@GovindaSharma 
Looks like this code already merged
https://github.com/magento/magento2/blame/2.3-develop/app/code/Magento/BundleGraphQl/Model/BundleProductTypeResolver.php

2019-02-19 20:21 UTC, naydav commented
The functionality has already been merged.

2019-02-19 20:21 UTC, closed without merging