GraphQL-272: [My Account] Added test address extractor
magento/graphql-ce pull request #358
Opened 2019-02-10 13:06 UTC by AleksLi

### Description (*)

Created a new PR for Create new address through GraphQL request. Started from Validate address on Created Address action.

### Fixed Issues (if relevant)

1. magento/magento2#<272>: [My Account] Add support of Customer Address attributes

Please give me your opinion and tell me if I'm doing something wrong.

2019-02-19 20:27 UTC, naydav commented
Hello @AleksLi,
Please check failed travis build
Also, need to cover functionality with API-functional tests
Thanks

2019-02-20 09:31 UTC, AleksLi commented
@naydav  Am I get the idea correctly?
Thank you. I wasn't sure I did everything right, that's why I didn't complete everything here. Now I will proceed and make sure the builds are green and api-functional tests are green

2019-03-23 20:04 UTC, AleksLi commented
@naydav I don't get what is wrong with the Dashboard:tunnel method in the builds. I think that's the common issue. I saw that in my other PRs and they disappeared suddenly somehow. Can you take a look, please?

2019-05-02 23:41 UTC, naydav commented
Hi @AleksLi,
Will you continue to work on the ticket?  Know it looks like the created code is not used anywhere

2019-05-02 23:42 UTC, naydav commented on app/code/Magento/CustomerGraphQl/Model/Customer/Address/CustomerAddressCreateDataValidator.php
> +            foreach ($errors as $messageText) {
What is the difference between `$errors` and `$errorInput`?

2019-05-02 23:44 UTC, naydav requested changes

2019-05-02 23:44 UTC, naydav commented on app/code/Magento/CustomerGraphQl/Model/Customer/Address/Validator.php
> +        $addressForm = $this->formFactory->create(
Could you check how it's work in REST api... looks not good when we use something like `form` in HTTP calls responsible area

2019-05-02 23:44 UTC, naydav commented on app/code/Magento/CustomerGraphQl/Model/Customer/Address/Validator.php
> +        return $this->requestFactory->create();
Redundant method

2019-05-02 23:44 UTC, naydav commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Customer/UpdateCustomerAddressTest.php
> +
Looks like it'is not enough for testing ))

2019-06-14 19:19 UTC, naydav commented
Hello @AleksLi,
PR was closed due to inactivity. Please reopen and update if you wish to continue. 
Thanks!

2019-06-14 19:19 UTC, closed without merging