Query category for disabled catalog with products returns the product count
magento/graphql-ce pull request #476
Opened 2019-03-15 11:05 UTC by XxXgeoXxX

### Description (*)
issue https://github.com/magento/graphql-ce/issues/463

### Manual testing scenarios (*)
#### Steps to reproduce (*)
Create Simple Product and assign it to any category that can be added to menu
Navigate to Catalog -> Categories and edit the category from previous step
Disable the category
Perform the query:
```
{
  category(id: {{ ID }} ) {
    product_count
  }
}
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-03-25 21:29 UTC, naydav commented
Has failed internal PAT builds
https://bamboo.corp.magento.com/browse/MCCE23-PAT2482-1
Need to additional time for investigate

2019-04-01 21:17 UTC, naydav commented
@XxXgeoXxX 
Could you run jmeter on a local machine?

2019-04-02 21:07 UTC, naydav commented
@XxXgeoXxX 
For reproducing this problem you can execute:
```
{
  category(id: 1) {
    name
    id
    level
    description
    path
    path_in_store
    url_key
    url_path
    children {
      id
      description
      default_sort_by
      children {
        id
        description
        level
        children {
          level
          id
          children {
            id
          }
        }
      }
    }
  }
}
```
Result:
```
{
  "errors": [
    {
      "debugMessage": "Notice: Undefined index: is_active in /var/www/graphql.local/docs/ce/app/code/Magento/CatalogGraphQl/Model/Resolver/CategoryTree.php on line 84",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "category"
      ]
    }
  ],
  "data": {
    "category": null
  }
}
```

2019-04-02 21:10 UTC, naydav commented
Generally, it is not a good idea to build a tree and just after that throw exception.
We can add `is_active` condition to query for loading tree

2019-04-03 17:11 UTC, naydav commented
\Magento\CatalogGraphQl\Model\Resolver\Products\DataProvider\CategoryTree::getTree
\Magento\CatalogGraphQl\Model\Category\LevelCalculator::calculate

2019-04-24 21:06 UTC, naydav commented
@XxXgeoXxX 
We have static tests failures
```
Magento\Test\Php\LiveCodeTest::testCodeMess
PHP Code Mess has found error(s):
/var/www/html/app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php:25	The class CategoryTree has a coupling between objects value of 14. Consider to reduce the number of dependencies under 13.
```
```
```

2019-04-27 09:46 UTC, XxXgeoXxX commented
Short description was added

2019-04-30 18:01 UTC, naydav commented
@XxXgeoXxX 
But still have
```
Magento\Test\Php\LiveCodeTest::testCodeMess
PHP Code Mess has found error(s):
/var/www/html/app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php:25	The class CategoryTree has a coupling between objects value of 14. Consider to reduce the number of dependencies under 13.
```

2019-05-08 12:48 UTC, rogyar requested changes

2019-05-08 12:48 UTC, rogyar commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php
> +     * @throws \Exception
Please, clarify the exception. It's rather `\Magento\Framework\Exception\LocalizedException` than `\Exception`

2019-05-08 12:48 UTC, rogyar commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php
> +        if ($this->isCategoryActive($rootCategoryId) == false) {
Please, use strict comparison operator in such cases (`===`). Technically, they are faster and if we use type casting (bool) we are sure that we are going to have a boolean type here in any case

2019-05-08 12:53 UTC, rogyar commented
Hi @XxXgeoXxX. Please, check my review comments.

But prior to fixing the issues, I would like to discuss the approach you've chosen. If we take a look at https://github.com/magento/graphql-ce/blob/5bf736481300478ed6ce2dfd3c3ac5dd6f19a5a9/app/code/Magento/CatalogGraphQl/Model/Resolver/CategoryTree.php#L77 - the logic is built in the way to have the error if categories collection is empty. So, I believe it's a good idea to stick with this approach instead of throwing the same exception twice. All we need to do is to make sure that the category collection is empty on requesting an inactive category.

At the same time, we already have `is_active` check here 

https://github.com/magento/graphql-ce/blob/62fd888833477a6bb35623e333f0e8798afb293f/app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php#L104

but looks like something goes wrong here.

So instead of introducing another `is_active` check for the collection, maybe we should fix the existing one and use the existing exception throwing flow?

I might miss something but just want to share my look on this matter. I'm always open to a discussion.

Thank you

2019-05-10 06:05 UTC, XxXgeoXxX commented
Hi @rogyar
changes were provided

2019-05-14 15:27 UTC, TomashKhamlai commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php
> +        if ($this->isCategoryActive($rootCategoryId) === false) {
Please cover this case:
category with "path": "1/2/3/4/5" has products assigned and is enabled
category with "path": "1/2/3/4" has no products assigned and is enabled
category with "path": "1/2/3" has no products assigned and is disabled

Assert 1: for category 3 product_count throws GraphQlNoSuchEntityException
Assert 2: for category 5 product_count throws GraphQlNoSuchEntityException
Assert 2 will fail.

2019-06-12 17:37 UTC, naydav approved these changes

2019-06-14 18:49 UTC, naydav commented
@XxXgeoXxX please look at failed static tests
Looks like we can move `isCategoryActive` method to separate class
Thanks

2019-06-21 16:20 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=476) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=476) before we can accept your contribution.<br/>**2** out of **15** committers have signed the CLA.<br/><br/>:white_check_mark: naydav<br/>:white_check_mark: lenaorobei<br/>:x: mKovdrysh<br/>:x: magento-devops-community-builds-svc<br/>:x: joanhe<br/>:x: soumyau<br/>:x: magento-cicd2<br/>:x: anthoula<br/>:x: kabothu<br/>:x: cpartica<br/>:x: magento-engcom-team<br/>:x: VladimirZaets<br/>:x: serhii-balko<br/>:x: yelahin-serhiy<br/>:x: diazwatson

2019-06-21 17:24 UTC, naydav requested changes

2019-06-21 17:24 UTC, naydav commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Category/CheckCategoryIsActive.php
> +        $collection->addAttributeToFilter(Category::KEY_IS_ACTIVE, ['eq' => 1])
Should bereplaced on `\Magento\Catalog\Api\Data\CategoryInterface::KEY_IS_ACTIVE`

2019-06-21 17:24 UTC, naydav commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Category/CheckCategoryIsActive.php
> +    public function execute(int $rootCategoryId): void
The more proper variable name is `categoryId`

2019-06-21 20:37 UTC, naydav approved these changes

2019-06-21 20:38 UTC, magento-engcom-team commented
Hi @naydav, thank you for the review.
[ENGCOM-4576](https://jira.corp.magento.com/browse/ENGCOM-4576) has been created to process this Pull Request
:eight_spoked_asterisk: @naydav, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-06-25 18:20 UTC, merged