Include 'products' in category query
magento/graphql-ce pull request #48
Opened 2018-05-21 19:25 UTC by facundocapua

### Description
As a Magento developer, I want to access the "products" directly from any category object so that it's easy for me to render products belonging to a category from that category object. 

**Acceptance criteria**
1. User can access products belonging to a category from that category object
1. There is a default limit on how many products are shown at a time so that performance is not hindered
1. User can access products beyond than those included in the default set by changing pagination or default pagesize
1. At least the following data is available: 
    * name
    * sku
    * product_type
    * description
    * short_description
    * media_gallery_entries (default medium or thumbnail image)
    * price (final calculated price)
    * review rating
    * custom_attribute (ex: featured, popular)
    * product_options
5. Changes are covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-05-21 19:25 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/signed)](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=48) <br/>All committers have signed the CLA.

2018-05-22 19:16 UTC, paliarush requested changes
@facundocapua thank you for contribution, please address a few comments and we should be good to merge the PR.

2018-05-22 19:16 UTC, paliarush commented on app/code/Magento/CatalogGraphQl/etc/schema.graphqls
> +    items: [ProductInterface] @doc(description: "An array of products that match the specified search criteria")
Search criteria is not used to fetch category products list. Please correct the docs.

2018-05-22 19:16 UTC, paliarush commented on app/code/Magento/CatalogGraphQl/Model/Resolver/Category/Products.php
> +class Products implements ResolverInterface
Please document the class.

2018-05-22 19:16 UTC, paliarush commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/CategoryTest.php
> +        $this->assertEquals(20, $response['category']['products']['page_info']['page_size']);
Please add assertions at least for the product attributes mentioned in the acceptance criteria. For one of the products should be enough.

2018-05-22 20:37 UTC, paliarush commented
- [ ] Please address build issue: https://travis-ci.com/magento/graphql-ce/jobs/125373510

2018-05-23 00:01 UTC, facundocapua commented
@paliarush I have addressed all your suggestions.

Please take a look and let me know.

Thanks for your comments!

2018-05-23 14:55 UTC, paliarush commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/CategoryTest.php
> +//            ['response_field' => 'weight', 'expected_value' => $product->getWeight()],
Please remove comment

2018-05-23 15:03 UTC, paliarush commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/CategoryTest.php
> +    private function eavAttributesToGraphQlSchemaFieldTranslator($attributeCode)
Unused method. Please remove.

2018-05-23 15:07 UTC, paliarush commented
@facundocapua the test looks great now! Please address couple minor comments and then we can merge the PR.

2018-05-23 17:09 UTC, facundocapua commented
@paliarush Thanks for you review!! I have removed unused code.

2018-05-24 14:32 UTC, paliarush approved these changes

2018-05-24 18:13 UTC, misha-kotov approved these changes
Approved

2018-05-24 19:04 UTC, paliarush commented
@facundocapua, please see if you can reproduce the failure which we have on our CI environment when running the whole web API test suite:

```
Magento\GraphQl\Catalog\CategoryTest::testCategoryProducts
Failed asserting that 1 matches expected 2.

/.../dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/CategoryTest.php:269
```

2018-05-28 16:16 UTC, merged

2018-05-29 20:38 UTC, paliarush commented
@vgelani thank you for merging the PR, however it cannot be delivered to `magento/magento2` repository yet because of failing test. It will be delivered after the test is fixed.

2018-05-31 05:31 UTC, paliarush commented
PR delivered to mainline. @facundocapua thank you for contribution!