New field resolver architecture proposal
magento/graphql-ce pull request #490
Opened 2019-03-16 12:55 UTC by rogyar

### Description (*)
The general idea of the current PR is starting decoupling from Webonyx.
Currently, within a scope of a resolver, we work with data provided by Webonyx directly. For example:
https://github.com/magento/graphql-ce/blob/7b1cd79738b2cff7881a8defe4a58c6142c8ed88/app/code/Magento/QuoteGraphQl/Model/Resolver/Cart.php#L38-L43

In order to start the decoupling process we need to get rid of the direct usage of the Webonyx data and introduce an intermediate layer (interface) with the corresponding set of getters/setters. At the very beginning the mentioned intermediate layer will work with Webonyx. However, in the future we can change the interface implementation to our own if necessary.

### Fixed Issues (if relevant)
1. #71 : Decouple from Webonyx

2019-03-26 01:33 UTC, naydav requested changes

2019-03-26 01:33 UTC, naydav commented on lib/internal/Magento/Framework/GraphQl/FieldResolverContextInterface.php
> +interface FieldResolverContextInterface
Please, rename to `QueryContextInterface`

2019-03-26 01:33 UTC, naydav commented on lib/internal/Magento/Framework/GraphQl/Query/QueryInterface.php
> +interface QueryInterface
Please finish description this and the other of Interface (including parameters and return values)

2019-03-26 01:33 UTC, naydav commented on lib/internal/Magento/Framework/GraphQl/Schema/Type/Output/ElementMapper/Formatter/Fields.php
> +            // TODO: Here the new resolver interface will be substituted.
Please, implement the approach for any resolver from `QuoteGraphQl` module

2019-03-26 01:33 UTC, naydav commented on lib/internal/Magento/Framework/GraphQl/Query/QueryInterface.php
> +    public function getArgs();
Rename to `getArguments`

2019-03-27 13:38 UTC, rogyar commented
Hi @naydav. I've implemented Cart resolver according to the new resolver structure. 
I have doubts about the necessity to introduce a new context interface/implementation since we already have one `\Magento\Framework\GraphQl\Query\Resolver\ContextInterface`. I've reused this interface in my example. However, if you have another point on this matter - I'm open for discussions.

Thank you!

2019-05-02 16:02 UTC, naydav commented
We are going to create a new more efficient way for filtration and loading data.
Creation of Design Document is in progress (#567).

So, need to wait to introduce a new mechanism and just after that continue work with this PR.

2019-05-02 16:02 UTC, closed without merging