Add API Test For Selected Shipping Method functionality
magento/graphql-ce pull request #491
Opened 2019-03-16 14:30 UTC by 06romix

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#478: Selected Shipping Method' functionality

### Manual testing scenarios (*)

1. N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-03-16 14:30 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/signed)](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=491) <br/>All committers have signed the CLA.

2019-03-19 15:35 UTC, TomashKhamlai commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/SelectedShippingMethodTest.php
> +     * @magentoApiDataFixture Magento/Checkout/_files/quote_with_address.php
I guess there should be annotation like
`* @expectedException \Magento\Framework\Exception\NoSuchEntityException`

2019-03-19 15:37 UTC, TomashKhamlai commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/SelectedShippingMethodTest.php
> +     * @magentoApiDataFixture Magento/Checkout/_files/quote_with_address.php
The same thing here

2019-03-25 17:39 UTC, naydav requested changes

2019-03-25 17:39 UTC, naydav commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/SelectedShippingMethodTest.php
> +    private $searchCriteriaBuilder;
Please, clear all of not used dependencies

2019-03-25 17:39 UTC, naydav commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/SelectedShippingMethodTest.php
> +    protected function getCart($reservedOrderId)
Looks like we don't need this method

2019-03-30 02:12 UTC, merged