graphQl-309: added agreement coverage
magento/graphql-ce pull request #504
Opened 2019-03-20 15:05 UTC by VitaliyBoyko

### Description (*)
Added coverage for checkout agreements.

Sample query: 
```
{
  checkoutAgreements {
    agreement_id
    name
    content
    content_height
    checkbox_text
    is_html
  }
}
```

2019-03-30 02:50 UTC, naydav commented
@galaoleksandr Pls, test this PR
Thanks

2019-04-16 21:35 UTC, naydav requested changes

2019-04-16 21:35 UTC, naydav commented on app/code/Magento/CheckoutAgreementsGraphQl/etc/module.xml
> +            <module name="Magento_GraphQl"/>
This sequence dependency is redundant

2019-04-16 21:35 UTC, naydav commented on app/code/Magento/CheckoutAgreementsGraphQl/etc/schema.graphqls
> +    checkoutAgreements: [CheckoutAgreement] @resolver(class: "Magento\\CheckoutAgreementsGraphQl\\Model\\Resolver\\CheckoutAgreements") @doc(description: "The Checkout Agreements query returns inform
`The Checkout Agreements query returns information about a Checkout Agreements`  :)

2019-04-16 21:35 UTC, naydav commented on dev/tests/api-functional/testsuite/Magento/GraphQl/CheckoutAgreements/Api/CheckoutAgreementsListTest.php
> +        $this->assertEquals(1, count($agreements));
`assertCount`

2019-04-16 21:35 UTC, naydav commented on app/code/Magento/CheckoutAgreementsGraphQl/Model/Resolver/CheckoutAgreements.php
> + * CMS page field resolver, used for GraphQL request processing
Please, fix description

2019-04-16 21:35 UTC, naydav commented on dev/tests/api-functional/testsuite/Magento/GraphQl/CheckoutAgreements/Api/CheckoutAgreementsListTest.php
> +    }
Please, add one test case: `try to get when agreements are not set. The result should be empty array`
Thanks

2019-04-16 21:35 UTC, naydav commented on app/code/Magento/CheckoutAgreementsGraphQl/Model/Resolver/DataProvider/CheckoutAgreements.php
> +        $this->searchCriteriaBuilder->addFilter(AgreementInterface::IS_ACTIVE, true);
Need to add support of `store` (with tests coverage)

Also, looks using the collection (which we can consider as query API)
```
$agreements = $this->agreementCollectionFactory->create();
$agreements->addStoreFilter($this->_storeManager->getStore()->getId()); // TODO: store should be get from query context
 $agreements->addFieldToFilter('is_active', 1);
```

2019-04-16 21:35 UTC, naydav commented on app/code/Magento/CheckoutAgreementsGraphQl/Model/Resolver/CheckoutAgreements.php
> +        $checkoutAgreementsData = $this->checkoutAgreementsDataProvider->getData();
Need to take into account `checkout/options/enable_agreements (Enable Terms and Conditions)` (should be covered with API-functional tests)
Pay attention option value could be per `store view`

2019-05-03 04:03 UTC, pmclain commented on app/code/Magento/CheckoutAgreementsGraphQl/etc/schema.graphqls
> +    is_html: Boolean @doc(description: "Is Checkout Agreement content in HTML format")
@naydav @VitaliyBoyko  I think we need to include `mode` here as an ENUM. In the existing checkout flow mode determines if a user must accept the agreements by clicking a checkbox input.
Current mode options: https://github.com/magento/graphql-ce/blob/e60d3a2d8ff3964510ecaa0f7617fa9e482236c4/app/code/Magento/CheckoutAgreements/Model/AgreementModeOptions.php#L10-L12

Rendering Logic
Template: https://github.com/magento/graphql-ce/blob/46bbdd0e3d5796e427899b96c189888423cb55d4/app/code/Magento/CheckoutAgreements/view/frontend/web/template/checkout/checkout-agreements.html#L10-L35
Component: https://github.com/magento/graphql-ce/blob/3fc2f9e4c9e558fd73a7999ddec74cd8efe45d93/app/code/Magento/CheckoutAgreements/view/frontend/web/js/view/checkout-agreements.js#L33-L35

2019-05-10 01:21 UTC, merged