282 shipping methods USPS
magento/graphql-ce pull request #537
Opened 2019-03-26 16:11 UTC by atwixfirster

magento/graphql-ce#282: [Shipping methods] Support of USPS shipping method

### Description (*)
Works with sandbox USPS account.

2019-03-27 11:08 UTC, atwixfirster commented
@naydav , I've a proposition for you here.

On my local environment I've used my USPS sandbox account.

May be a good idea to have the appropriate one for Magento test instance. To provide USPS credentials and hide them from the 3rd eyes my proposition is use 
`dev/tests/api-functional/config/config-global.php` config file with the next content (for USPS):
```
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

return [
    'carriers' => [
        'usps' => [
            'userid' => '0:3:xxxxxxxx==',
            'password' => '0:3:yyyyyyyyy==',
        ]
    ]
];
```

where `0:3:xxxxxxxx==` is an encoded `User ID` and `0:3:yyyyyyyyy==` is an encoded account `Password`.

Please let me know your thoughts. 

Thank you!

2019-03-29 23:16 UTC, naydav requested changes

2019-03-29 23:16 UTC, naydav commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Usps/SetUspsShippingMethodsOnCartTest.php
> +    const CARRIER_METHOD_CODE_GROUND = '4';
Need to create `@dataprovider` and cover all of possible metods

2019-04-17 12:03 UTC, atwixfirster commented
@naydav , ticket is ready for your review.

Thank you!

2019-05-02 23:17 UTC, naydav requested changes
@atwixfirster 
As we talk early, need to introduce some mock object instead of 'real caller' object
Our tests should not depend on external system

The best way is creating preference in GraphQLTestModule and replace real object on our internal mock object

2019-06-13 17:35 UTC, lenaorobei approved these changes

2019-06-13 17:36 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-5284](https://jira.corp.magento.com/browse/ENGCOM-5284) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-06-13 19:55 UTC, naydav approved these changes

2019-06-13 19:56 UTC, magento-engcom-team commented
Hi @naydav, thank you for the review.
[ENGCOM-5284](https://jira.corp.magento.com/browse/ENGCOM-5284) has been created to process this Pull Request
:eight_spoked_asterisk: @naydav, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-06-14 20:05 UTC, naydav approved these changes

2019-06-14 20:06 UTC, magento-engcom-team commented
Hi @naydav, thank you for the review.
[ENGCOM-5284](https://jira.corp.magento.com/browse/ENGCOM-5284) has been created to process this Pull Request

2019-06-19 01:11 UTC, merged