Add API functional tests for ApplyCouponToCart functionality
magento/graphql-ce pull request #558
Opened 2019-04-01 17:35 UTC by dmytro-ch

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#479: [Test Coverage] 'ApplyCouponToCart' functionality

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-02 21:29 UTC, naydav requested changes

2019-04-02 21:29 UTC, naydav commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/ApplyCouponToCartTest.php
> +    protected $couponResource;
Please, check and remove all of unused dependencies like this

2019-04-02 21:29 UTC, naydav commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/ApplyCouponToCartTest.php
> +    private function excludeProductPerCoupon(string $couponCode, string $sku)
Could we move this `set-up` to fixture file (with rollback)?

Example:
```
/**
     * @magentoApiDataFixture Magento/Customer/_files/customer.php
     * @magentoApiDataFixture Magento/Catalog/_files/product_simple.php
     * @magentoApiDataFixture Magento/GraphQl/Quote/_files/customer/create_empty_cart.php
     * @magentoApiDataFixture Magento/GraphQl/Quote/_files/add_simple_product.php
     * @magentoApiDataFixture Magento/GraphQl/Quote/_files/set_new_shipping_address.php
     */
```

2019-04-02 21:29 UTC, naydav commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/ApplyCouponToCartTest.php
> +        $maskedQuoteId = $this->quoteIdToMaskedId->execute((int)$this->quote->getId());
Looks like we can avoid manipulating with QuoteResource (etc..) if we will reuse current fixtures
```
/**
     * @magentoApiDataFixture Magento/Customer/_files/customer.php
     * @magentoApiDataFixture Magento/Catalog/_files/product_simple.php
     * @magentoApiDataFixture Magento/GraphQl/Quote/_files/customer/create_empty_cart.php
     * @magentoApiDataFixture Magento/GraphQl/Quote/_files/add_simple_product.php
     * @magentoApiDataFixture Magento/GraphQl/Quote/_files/set_new_shipping_address.php
     */
```

2019-04-03 02:04 UTC, naydav commented
@dmytro-ch 
I finished one more related example
https://github.com/magento/graphql-ce/pull/497/files

2019-04-07 20:05 UTC, dmytro-ch commented
Hello @naydav,
thank you for reviewing this PR.
I've applied the changes according to the recommendations.

Thank you!

2019-04-09 09:21 UTC, merged