Update cart items with customizable options
magento/graphql-ce pull request #626
Opened 2019-04-24 12:53 UTC by rogyar

### Description (*)
This PR introduces a possibility to update customisable options for cart items using `updateCartItems` mutation. 

### Fixed Issues (if relevant)

1. #622: Add possibility to update customizable_options in updateCartItems mutation

### Manual testing scenarios (*)
1. Create empty cart
2. Add a product to the shopping cart with customizable options
3. Use `updateCartItems` mutation to update the customizable options in the following way

```graphql
mutation {
  updateCartItems(input: {
    cart_id:"$maskedCartId"
    cart_items: [
      {
        cart_item_id:23
        quantity:-1
        customizable_options: [
          {
            id:1
            value:"test"
          }
        ]
      }
    ]
  }) {
    cart {
      items {
        qty
        product {
          name
        }
        ... on SimpleCartItem {
          customizable_options {
            label
            values {
              label
              value
            }
          }
        }
      }
    }
  }
}
```

2019-05-02 23:38 UTC, naydav requested changes
@rogyar, please, align code to last changes in mainline
thanks
Also, need to cover functionality with API-functional tests

If you would like you can create a separate ticket for this

2019-05-03 13:46 UTC, rogyar commented
I'm currently working on the tests. Thank you

2019-05-08 10:30 UTC, rogyar commented on app/code/Magento/QuoteGraphQl/Model/Resolver/UpdateCartItems.php
> -    private function validateCartItem(Item $cartItem): void
Please note that all the validations and error handling are moved here https://github.com/magento/graphql-ce/pull/626/files#diff-23947b0596c6c269244b8667cb99db1aR46

2019-05-08 14:08 UTC, rogyar commented
Api-functional tests for this feature are done. I will fix other api-functional tests soon.

2019-05-08 19:09 UTC, naydav commented
Merged last mainline

2019-05-10 13:39 UTC, TomashKhamlai commented
@rogyar could you please share your knowledge? What does it mean `@group recent`?

2019-05-10 14:17 UTC, TomashKhamlai commented
Tried to update Virtual Product with multiple customizable option and something always goes wrong for me.  
The response is:
```graphql
{
  "errors": [
    {
      "message": "Could not update cart item: The product's required option(s) weren't entered. Make sure the options are entered and try again.",
      "category": "graphql-input",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "updateCartItems"
      ]
    }
  ],
  "data": {
    "updateCartItems": null
  }
}
```
Fixture `Magento/GraphQl/Catalog/_files/set_custom_options_simple_product.php` covers `area` and `field` customizable options.

It looks like multiple and checkbox are not covered.

2019-05-10 14:34 UTC, TomashKhamlai commented
I found that after every update request that succeeded the `cart_item_id` is incremented. Please check that it is expected result of successful operation.

2019-05-11 18:29 UTC, rogyar commented
Hi @TomashKhamlai. As for incremented `cart_item_id` - it's expected behavior as I described in the description. The same happens when you edit an item from the storefront. If an item's options were changed, the quote item is being recreated with a new set of options and a new `cart_item_id`. 
As for the multiselect options, I will check it out, thank you.

2019-05-19 14:10 UTC, rogyar commented
Hi @TomashKhamlai. I've just added support for multi-select custom options as well

2019-06-24 21:18 UTC, naydav approved these changes

2019-06-24 21:19 UTC, magento-engcom-team commented
Hi @naydav, thank you for the review.
[ENGCOM-5349](https://jira.corp.magento.com/browse/ENGCOM-5349) has been created to process this Pull Request
:eight_spoked_asterisk: @naydav, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-06-25 18:20 UTC, merged