GraphQL-672: Change customer password
magento/graphql-ce pull request #705
Opened 2019-05-12 19:40 UTC by rafaelstz

https://github.com/magento/graphql-ce/issues/672

Test cases:

```
\Magento\GraphQl\Customer\ChangeCustomerPasswordTest
- testChangePasswordIfCurrentPasswordIsEmpty
- testChangePasswordIfNewPasswordIsEmpty
- testChangePasswordIfCustomerIsLocked (see \Magento\GraphQl\Customer\UpdateCustomerTest::lockCustomer)
- tesChangeCustomerAddressIfAccountIsNotConfirmed
```

2019-05-12 19:40 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=705) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=705) before we can accept your contribution.<br/>

2019-06-04 22:23 UTC, lenaorobei approved these changes

2019-06-04 22:24 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-5207](https://jira.corp.magento.com/browse/ENGCOM-5207) has been created to process this Pull Request

2019-06-06 14:52 UTC, lenaorobei commented
@magento run all tests

2019-06-06 15:29 UTC, lenaorobei requested changes
@rafaelstz could you please address WebAPI Tests build issue. Thanks.
```
Failed asserting that exception message 'GraphQL response contains errors: Specify the "newPassword" value.
' contains 'Account is not confirmed.'.
```

2019-06-10 19:01 UTC, lenaorobei commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Customer/ChangeCustomerPasswordTest.php
> +        $this->assertEquals($customerEmail, $response['changePassword']['email']);
Looks like should be `changeCustomerPassword`.

2019-06-10 23:02 UTC, lenaorobei approved these changes

2019-06-10 23:03 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-5207](https://jira.corp.magento.com/browse/ENGCOM-5207) has been created to process this Pull Request

2019-06-19 01:11 UTC, merged