Fix for config variant stock 736
magento/graphql-ce pull request #747
Opened 2019-06-18 13:17 UTC by minesh93

### Description
This will show product variation if the configuration value of `cataloginventory/options/show_out_of_stock` is set to 1.

Out of stock items are then filtered out via `Magento\CatalogInventory\Helper\Stock::addInStockFilterToCollection`

### Fixed Issues
1. #736 Configurable products with "out of stock" return as product: null

### Manual testing scenarios (*)
Create a configurable product with one of the variants being out of stock. Test with both `cataloginventory/options/show_out_of_stock` being enabled and disabled.

2019-06-18 13:17 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=747) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=747) before we can accept your contribution.<br/><hr/>**Minesh Mitha** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2019-06-18 15:18 UTC, naydav requested changes

2019-06-18 15:18 UTC, naydav commented on app/code/Magento/ConfigurableProductGraphQl/Model/Variant/Collection.php
> +    protected $stockConfig;
Should be private

2019-06-18 15:18 UTC, naydav commented on app/code/Magento/ConfigurableProductGraphQl/Model/Variant/Collection.php
> +            if (!$showOutOfStock) {
@minesh93, please cover this functionality with API-functional tests
thanks

Examples:
https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Customer
https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer

Guide:
https://devdocs.magento.com/guides/v2.3/graphql/functional-testing.html

2019-06-28 16:38 UTC, naydav approved these changes

2019-06-28 16:39 UTC, magento-engcom-team commented
Hi @naydav, thank you for the review.
[ENGCOM-5372](https://jira.corp.magento.com/browse/ENGCOM-5372) has been created to process this Pull Request
:eight_spoked_asterisk: @naydav, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-06-28 16:39 UTC, magento-engcom-team commented
@minesh93 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

2019-07-11 15:08 UTC, merged