magento/graphql-ce:#678 Send email to friend
magento/graphql-ce pull request #752
Opened 2019-06-22 12:38 UTC by rleshchenko

### Description (*)

### Fixed Issues (if relevant)

1. magento/magento2#<#678>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-06-22 12:38 UTC, magento-cicd2 commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/not_signed)](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=752) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/graphql-ce?pullRequest=752) before we can accept your contribution.<br/>

2019-06-22 13:19 UTC, vpodorozh requested changes
Please check my comments and fix static tests.
Thx!

2019-06-22 13:19 UTC, vpodorozh commented on app/code/Magento/SendFriendGraphQl/Model/Resolver/SendEmailToFriend.php
> +        ?Visibility $visibility= null
Backward compatibility should not be followed in GraphQL php codebase - only schema counted as a contract.
https://github.com/magento/graphql-ce/wiki/Approach-to-Implementation#backward-compatibility-policy

2019-06-22 13:19 UTC, vpodorozh commented on app/code/Magento/SendFriendGraphQl/Model/Resolver/SendEmailToFriend.php
> +        $this->visibility = $visibility ?: ObjectManager::getInstance()->create(Visibility::class);
check prev comment

2019-06-22 13:28 UTC, vpodorozh commented
@rleshchenko - please move `\Magento\SendFriendGraphQl\Model\Resolver\SendEmailToFriend::getProduct` into separate service. thx - this will eliminate two dependencies that break tests

2019-06-22 13:47 UTC, rleshchenko commented
@vpodorozh, I've refactored code according to your notes. Please look again

2019-06-22 13:47 UTC, rleshchenko commented on app/code/Magento/SendFriendGraphQl/Model/Resolver/ProductService.php
> +}
```suggestion
}

```

2019-06-22 13:48 UTC, rleshchenko commented on app/code/Magento/SendFriendGraphQl/Model/Resolver/ProductService.php
> +
```suggestion
```

2019-06-22 14:24 UTC, rleshchenko commented on app/code/Magento/SendFriendGraphQl/Model/Resolver/ProductService.php
> +
```suggestion
```

2019-06-22 14:49 UTC, vpodorozh requested changes

2019-06-22 14:49 UTC, vpodorozh commented on app/code/Magento/SendFriendGraphQl/Model/Resolver/ProductService.php
> +class ProductService
@rleshchenko:
1. could you please use the `Command` pattern for this.
Like - class name `GetProduct` and only one method is present called `execute`.

2. Please move to `Provider` directory - for example `\Magento\PaypalGraphQl\Model\Provider\Config` (sorry that I did not mention it earlier)

2019-06-24 18:33 UTC, vpodorozh commented
@novikor - please pick up this PR.
Everything seems to be ok from my point of view - so can you just approve it? (from now I do not have permissions any more)

Thx!

2019-06-24 20:12 UTC, lenaorobei commented
@rleshchenko thank you for the contribution. Few changes I made to your PR:
 - merged @pmclain `pmclain:issue/732` branch to your PR since you both were fixing `SendFriend` module;
- resolved conflicts;
- fixed expected exception message in the `api-functional test`.

2019-06-24 21:05 UTC, naydav approved these changes

2019-06-25 18:20 UTC, merged