Added DateTypePool and dataTypes in array di.xml
magento/graphql-ce pull request #771
Opened 2019-07-08 14:41 UTC by sedonik

### Description (*)

Added Magento\CatalogGraphQl\Model\Product\Option\DateTypePool class.
Added dataTypes array (Y-m-d, Y-m-d H:i:s, Y-m-d H:i:s) in di.xml.
Implemented DI for DateTypePool with the constructor.

### Fixed Issues

1. magento/graphql-ce#761: [Customizable Options] Call to a member function format() on boolean

### Manual testing scenarios (*)

1. Create Simple Product similar to :
SKU: simple-product-1
qty: 100500
Customizable options:
type: date

2. Perform query for Customer and use header
Header:

```
{
  "Authorization": "Bearer {{ CUSTOMER_TOKEN }}"
}
```

Query:

```
mutation {
  addSimpleProductsToCart(
    input: {
      cart_id: "{{ CART_ID }}"
      cart_items: {
        data: {
          quantity: 1
          sku: "simple-product-3"
        }
        customizable_options: [
          {
            id: 1
            value_string: "12-12-12"
          }
        ]
      }
    }
  ) {
    cart {
      items {
        quantity
        product {
          sku
        }
      }
    }
  }
}
```
3. Product was added to cart

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-07-09 04:38 UTC, fooman commented on app/code/Magento/CatalogGraphQl/etc/di.xml
> +                <item name="time" xsi:type="string">Y-m-d H:i:s</item>
Not sure if date_time and time are the same format on purpose.

2019-07-17 19:31 UTC, lenaorobei commented
@magento run all tests

2019-07-22 20:38 UTC, lenaorobei commented
Hi @sedonik! Thanks for your contribution, however I have few concerns regarding the expected behavior. It would be more obvious to see error message like `Invalid format provided. Please use 'Y-m-d' for 'date' type instead of formatting. The same for `date-time` and `time` https://github.com/magento/graphql-ce/issues/761#issuecomment-513943024

Could you please address this concern and update your PR? Thank you.

2019-07-30 20:36 UTC, lenaorobei commented
@sedonik, how is your progress with this ticket, are you interested to finish it?

2019-07-30 20:36 UTC, lenaorobei requested changes
@sedonik, how is your progress with this ticket, are you interested to finish it?

2019-08-01 22:21 UTC, sedonik commented
Hi @lenaorobei,

Sorry for the late response. I was on a vacation. I'm very interested to finish the task. 

I've updated PR with new [commit](https://github.com/magento/graphql-ce/pull/771/commits/7a9eedb72ffe55945f5768b7d434ec78af5a10c2).

Am I in the correct way? Pls, advice.

2019-08-05 17:02 UTC, lenaorobei commented
@sedonik, pool is redundant here, so if date cannot be crated with `DateTime::DATETIME_PHP_FORMAT` than we need to throw a `GraphQlInputException `. We don't want to hide formatting logic and try to transform any value to the date.

2019-08-05 21:06 UTC, sedonik commented
It is not very clear what logic should be implemented. 
Customizable Option in our case has next types: 'date', 'date_time' and 'time'. Any of these types has its own format. That's why I created Pool of Date Types. 

Seems like it has the sense to create new [PR](https://github.com/magento/graphql-ce/pull/804).
@lenaorobei  could you take look and correct/tell if it needs to add some modifications.

Thanks.

2019-08-06 14:01 UTC, lenaorobei commented
@sedonik yes https://github.com/magento/graphql-ce/pull/804 looks good to me.

2019-08-06 14:01 UTC, closed without merging