Customer downloadable products GraphQL
magento/graphql-ce pull request #802
Opened 2019-08-05 14:46 UTC by ldusan84

### Description (*)

Moved customer downloadable products into a new module and added tests.

### Fixed Issues (if relevant)

1. magento/magento2#685: Extract logic related to customer from DownloadableGraphQl module into new one

### Manual testing scenarios (*)

1. Get token as customer:

```
mutation {
  generateCustomerToken(
    email: "customer@example.com"
    password: "password"
  ) {
    token
  }
}
```
2. Get customer's downloadable products:
```
{
    customerDownloadableProducts{
        items{
            order_increment_id
            date
            status
            download_url
            remaining_downloads
        }
    }
}
```

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-05 19:06 UTC, lenaorobei requested changes
Please address my comments and remove duplicated tests `\Magento\GraphQl\Downloadable\CustomerDownloadableProductsTest`.

2019-08-05 19:06 UTC, lenaorobei commented on app/code/Magento/CustomerDownloadableGraphQl/composer.json
> +        "php": "~7.1.3||~7.2.0",
``` suggestion
        "php": "~7.1.3||~7.2.0||~7.3.0",
```

2019-08-05 19:06 UTC, lenaorobei commented on app/code/Magento/CustomerDownloadableGraphQl/etc/schema.graphqls
> +}
``` suggestion
}

```

2019-08-05 19:06 UTC, lenaorobei commented on dev/tests/api-functional/testsuite/Magento/GraphQl/CustomerDownloadableProduct/CustomerDownloadableProductTest.php
> +    public function testGetCustomerDownloadableProducts()
This test can be simplified. Please have a look at `\Magento\GraphQl\Downloadable\CustomerDownloadableProductsTest::testCustomerDownloadableProducts`.

2019-08-10 14:15 UTC, ldusan84 commented
@lenaorobei I changed the things that you mentioned, please check.

2019-08-14 19:47 UTC, lenaorobei commented
@ldusan84 could you please pull latest mainline changes. We delivered recently https://github.com/magento/graphql-ce/pull/412 and it will impact your PR.

2019-08-16 21:05 UTC, ldusan84 commented
@lenaorobei that's done.

2019-08-27 21:46 UTC, lenaorobei approved these changes

2019-08-27 21:48 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-5718](https://jira.corp.magento.com/browse/ENGCOM-5718) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-08-28 15:13 UTC, lenaorobei commented
@magento run Functional Tests build

2019-08-29 23:11 UTC, merged