Improve experience of interactive GraphQL schema exploration
magento/graphql-ce pull request #826
Opened 2019-08-14 16:26 UTC by TomashKhamlai

### Description (*)

Provide useful tips for those who explore GraphQL schema interactively.

### Fixed Issues (if relevant)

1. magento/graphql-ce#655: Add/Update docblock descriptions in GraphQL schema for modules related to Quote operations

### Manual testing scenarios (*)

1. Check that now it is clear which types were deprecated in autocomplete dropdown in GraphQL Playground

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-08-14 21:17 UTC, lenaorobei requested changes
@TomashKhamlai looks like your PR contains redundant commits.

2019-08-14 21:17 UTC, lenaorobei commented on app/code/Magento/ConfigurableProductGraphQl/etc/schema.graphqls
> +type ConfigurableCartItem implements CartItemInterface @doc(description: "Configurable Cart Item"){
Please add more explanatory doc here.

2019-08-14 21:17 UTC, lenaorobei commented on app/code/Magento/QuoteGraphQl/etc/schema.graphqls
> +    selected_payment_method: SelectedPaymentMethod @resolver(class: "\\Magento\\QuoteGraphQl\\Model\\Resolver\\SelectedPaymentMethod") @doc(description: "Selected payment method")
Same here.

2019-08-15 12:01 UTC, closed without merging

2019-08-15 13:17 UTC, TomashKhamlai commented
Closed #655