#820: return Out Of Stock Status if downloadable has no links
magento/graphql-ce pull request #868
Opened 2019-08-28 09:02 UTC by vovsky

PR fixes bug when stock status of downloadable product is In_Stock despite product has no links.

### Fixed Issues (if relevant)
1. magento/graphql-ce#820: Downloadable Product should be OUT OF STOCK if there are no links just samples saved

2019-08-28 20:47 UTC, lenaorobei reviewed
Please address my comment and cover this case with api functional test.
Thanks.

2019-08-28 20:47 UTC, lenaorobei commented on app/code/Magento/CatalogInventoryGraphQl/Model/Resolver/StockStatusProvider.php
> -        return $productStockStatus === StockStatusInterface::STATUS_IN_STOCK ? 'IN_STOCK' : 'OUT_OF_STOCK';
I think we need to check something like `$product->isInStock() && $product->isSaleable()`.

2019-09-11 20:16 UTC, lenaorobei approved these changes

2019-09-11 20:17 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-5830](https://jira.corp.magento.com/browse/ENGCOM-5830) has been created to process this Pull Request

2019-09-12 06:35 UTC, vovsky commented on app/code/Magento/CatalogInventoryGraphQl/Model/Resolver/StockStatusProvider.php
> -        return $productStockStatus === StockStatusInterface::STATUS_IN_STOCK ? 'IN_STOCK' : 'OUT_OF_STOCK';
@lenaorobei 
Unfortunately $product->isInStock() and $product->isSaleable() returns true for Out of Stock simple product, both methods check product status and not a stock :(
So currently I don't see how can we avoid using deprecated StockStatus interfaces

2019-09-12 15:01 UTC, lenaorobei commented on app/code/Magento/CatalogInventoryGraphQl/Model/Resolver/StockStatusProvider.php
> -        return $productStockStatus === StockStatusInterface::STATUS_IN_STOCK ? 'IN_STOCK' : 'OUT_OF_STOCK';
Yes, my recommendation was incorrect, sorry about that. Looks like the root cause is somewhere `\Magento\CatalogInventory\Model\StockRegistryProvider::getStockStatus` Need to debug and understand, why it does not take `saleable` into account.

2019-09-12 15:02 UTC, lenaorobei requested changes
Please address found issue.

2019-10-01 11:42 UTC, lenaorobei commented
Closing this PR due to inactivity. Please feel free to reopen to continue working on it. Thank you.

2019-10-01 11:42 UTC, closed without merging