graphQl-892: Improved strict typing in CartAddressInterface
magento/graphql-ce pull request #897
Opened 2019-09-04 07:26 UTC by VitaliyBoyko

### Description (*)
Improved strict typing in CartAddressInterface.

### Fixed Issues (if relevant)
1. #892: [Checkout] Improve strict typing in CartAddressInterface

2019-09-04 08:43 UTC, VitaliyBoyko commented
Looks like we have the same issue for the billing address as for the shipping address here #864.

2019-09-04 13:29 UTC, VitaliyBoyko commented
Hi @paliarush please clarify what should be returned in the scope of this case \Magento\GraphQl\Quote\Customer\GetSpecifiedBillingAddressTest::testGetSpecifiedBillingAddressIfBillingAddressIsNotSet. So far it returns object with nullable fields. As far as I have understood it should be null instead of an object.

2019-09-05 18:27 UTC, lenaorobei requested changes
@VitaliyBoyko billing address should be `null`. Please consider fixing api-functional test.

2019-10-11 21:04 UTC, lenaorobei commented on app/code/Magento/QuoteGraphQl/Model/Resolver/BillingAddress.php
> +        if (null === $billingAddress ||
Could you please use `validateAddressFromSchema` method? I mean move it to the separate class from  `\Magento\QuoteGraphQl\Model\Resolver\ShippingAddresses` and reuse for both - shipping and billing.

2019-10-11 21:04 UTC, lenaorobei requested changes
Please see my suggestion with `validateAddressFromSchema` method.

2019-10-14 20:18 UTC, lenaorobei approved these changes

2019-10-22 15:38 UTC, merged