graphQl-890: Replaced usage of the CartItemQuantity with the CartItem…
magento/graphql-ce pull request #899
Opened 2019-09-04 08:32 UTC by VitaliyBoyko

…Interface
### Description (*)
Replaced usage of the CartItemQuantity with the CartItemInterface in the GraphQl scheme.

### Fixed Issues (if relevant)
1. #890: [Checkout] Replace usage of CartItemQuantity with CartItemInterface

2019-09-04 15:57 UTC, lenaorobei approved these changes

2019-09-04 15:58 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-5772](https://jira.corp.magento.com/browse/ENGCOM-5772) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-09-10 19:38 UTC, lenaorobei requested changes
Could you please pull latest changes from `2.3-develop`

2019-09-13 07:05 UTC, VitaliyBoyko commented
@lenaorobei Done

2019-09-20 18:25 UTC, lenaorobei requested changes
Please address comments.

2019-09-20 18:25 UTC, lenaorobei commented on app/code/Magento/QuoteGraphQl/etc/schema.graphqls
> +    items_weight: Float @deprecated
Please add `reason` here.

2019-09-20 18:25 UTC, lenaorobei commented on app/code/Magento/QuoteGraphQl/etc/schema.graphqls
> +type CartItemQuantity @deprecated(reason: "Use CartItemInterface instead") {
From the ticket: 
> All fields in CartItemQuantity should be deprecated (so this type can be completely removed in the future releases)

2019-10-14 18:30 UTC, lenaorobei requested changes
Please add test case to check `shipping_addresses` field.

2019-10-28 15:45 UTC, lenaorobei approved these changes

2019-10-31 03:01 UTC, merged