Added description BraintreeInput
magento/graphql-ce pull request #909
Opened 2019-09-05 21:16 UTC by sedonik

### Description (*)

Braintree payment method input has multiple fields like: device_data, is_active_payment_token_enabler, payment_method_nonce which don't have the description.

### Issue

1. magento/graphql-ce#876: [Braintree] Add description to BraintreeInput

2019-09-06 13:45 UTC, lenaorobei requested changes
The description should provide clear understanding of the field purpose.

2019-09-06 14:27 UTC, YevSent requested changes

2019-09-06 14:27 UTC, joni-jones commented on app/code/Magento/BraintreeGraphQl/etc/schema.graphqls
> +    payment_method_nonce: String! @doc(description:"Required input for Braintrees payments")
Unfortunately, the added description doesn't explain the field purpose.
The `payment_method_nonce` is a one-time payment token generated by Braintree payment gateway based on card details and this token is required to make sale transaction.

2019-09-06 14:27 UTC, joni-jones commented on app/code/Magento/BraintreeGraphQl/etc/schema.graphqls
> +    is_active_payment_token_enabler: Boolean! @doc(description:"Required input for Braintrees payments")
This field is required only if Vault is enabled for Braintree payment integration. The `is_active_payment_token_enabler` shows if an entered by a customer credit/debit card should be tokenized for later usage.

2019-09-06 14:27 UTC, joni-jones commented on app/code/Magento/BraintreeGraphQl/etc/schema.graphqls
> +    device_data: String @doc(description:"Additional information for Braintrees payments")
The `device_data` will be presented only in a case if Kount (advanced fraud protection) is enabled for Braintree payment integration. The device data contains a fingerprint provided by Braintree JS SDK and should be sent with sale transaction details to the Braintree payment gateway.

2019-09-13 21:01 UTC, sedonik commented
@lenaorobei, @joni-jones 
Descriptions are updated. 
Could you check?

2019-09-14 14:58 UTC, lenaorobei requested changes
Please see my suggestions.

2019-09-14 14:58 UTC, lenaorobei commented on app/code/Magento/BraintreeGraphQl/etc/schema.graphqls
> +    is_active_payment_token_enabler: Boolean! @doc(description:"This field states whether an entered by a customer credit/debit card should be tokenized for later usage. Required only if Vault is ena
```suggestion
    is_active_payment_token_enabler: Boolean! @doc(description:"States whether an entered by a customer credit/debit card should be tokenized for later usage. Required only if Vault is enabled for Braintree payment integration.")
```

2019-09-14 14:58 UTC, lenaorobei commented on app/code/Magento/BraintreeGraphQl/etc/schema.graphqls
> +    device_data: String @doc(description:"This field contains a fingerprint provided by Braintree JS SDK and should be sent with sale transaction details to the Braintree payment gateway. The device_
```suggestion
    device_data: String @doc(description:"Contains a fingerprint provided by Braintree JS SDK and should be sent with sale transaction details to the Braintree payment gateway. Should be specified only in a case if Kount (advanced fraud protection) is enabled for Braintree payment integration.")
```

2019-09-18 23:12 UTC, lenaorobei approved these changes

2019-09-18 23:13 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-5859](https://jira.corp.magento.com/browse/ENGCOM-5859) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-09-25 02:36 UTC, merged