graphQl-903: deprecated use_for_shipping in billing address schema
magento/graphql-ce pull request #943
Opened 2019-09-18 13:19 UTC by VitaliyBoyko

# Fixed Issues (if relevant)
1. #903: [Checkout] Replace use_for_shipping with same_as_shipping

2019-09-18 23:04 UTC, lenaorobei commented on app/code/Magento/QuoteGraphQl/etc/schema.graphqls
> +    same_as_shipping: Boolean
Please add `@doc` here.

2019-09-27 09:48 UTC, lenaorobei commented on app/code/Magento/QuoteGraphQl/etc/schema.graphqls
> +    use_for_shipping: Boolean @doc(description: "Deprecated. Use same_as_shipping")
```suggestion
    use_for_shipping: Boolean @doc(description: "Deprecated: use `same_as_shipping` field instead")
```

2019-09-27 10:53 UTC, lenaorobei approved these changes

2019-09-27 10:54 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-5963](https://jira.corp.magento.com/browse/ENGCOM-5963) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-10-01 10:56 UTC, lenaorobei requested changes
Despite the fact that `use_for_shipping` is deprecated we need to preserve its behaviour. It should be the same as `same_as_shipping`.

2019-10-07 09:17 UTC, lenaorobei commented on app/code/Magento/QuoteGraphQl/Model/Cart/SetBillingAddressOnCart.php
> +        $sameAsShipping = isset($billingAddressInput['same_as_shipping'])
We need to keep `use_for_shipping` for BC. So, if `same_as_shipping ` is not specified, but `use_for_shipping` the code should still work as expected. But if both are specified - `same_as_shipping` should be preferred.

2019-10-07 09:18 UTC, lenaorobei commented on dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/SetBillingAddressOnCartTest.php
> -         use_for_shipping: true
We should keep tests for both fields for now.

2019-10-07 09:18 UTC, lenaorobei requested changes
Please see my comment about BC.

2019-10-23 20:13 UTC, lenaorobei approved these changes

2019-10-23 20:14 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-5963](https://jira.corp.magento.com/browse/ENGCOM-5963) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-10-31 03:01 UTC, merged