Absolute and relative path passed as argument return matching fields
magento/graphql-ce pull request #95
Opened 2018-06-14 16:36 UTC by adexandros

### Description

### Fixed Issues (if relevant)

1. urlResolver support for absolute paths#79

### Manual testing scenarios

1. Passed absolute and relative paths for CMS, Product and Category pages
2. Got always same response with the additional absolute_path field

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-06-19 22:06 UTC, paliarush requested changes
@adexandros Thanks for the PR.

1. Please cover changes with web API functional tests (at least positive)
2. This PR will conflict with https://github.com/magento/graphql-ce/pull/94 , please consider consolidating them. Then we will avoid merge conflicts and will be able to deliver them faster.

2018-06-19 22:06 UTC, paliarush commented on app/code/Magento/UrlRewriteGraphQl/Model/Resolver/UrlRewrite.php
> +            if ($parsedUrl['path'][0] === '/' && $parsedUrl['path'] !== '/') {
`$url` variable can be used here as before, no need to change lines 78-79 (from the original revision).

2018-10-09 12:48 UTC, naydav commented
Hi @adexandros,
I would like to ask you to finish this PR
Of course, if that doesn't bother you
Thanks

2018-11-13 15:35 UTC, naydav commented
Will be merge in scope of https://github.com/magento/graphql-ce/pull/208

2018-11-13 15:35 UTC, closed without merging