#913 - Deprecated the gender column
magento/graphql-ce pull request #954
Opened 2019-09-22 10:31 UTC by strell

### Description
 - Added new field genderV2 with the type of enum
 - Added data mapper in order to turn the gender value into genderV2 value and vice-versa
 - Extended api-functional tests

### Fixed Issues
1. magento/graphql-ce#913: [Customer] Convert gender type to enum

### Manual testing scenarios
See issue description

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-09-24 18:58 UTC, lenaorobei requested changes
Please address review comments.

2019-09-24 18:58 UTC, lenaorobei commented on app/code/Magento/CustomerGraphQl/etc/schema.graphqls
> +    genderV2: CustomerGenderEnum @doc(description: "The customer's gender")
```suggestion
    gender_v2: CustomerGenderEnum @doc(description: "The customer's gender")
```

2019-09-24 18:58 UTC, lenaorobei commented on app/code/Magento/CustomerGraphQl/etc/schema.graphqls
> +    genderV2: CustomerGenderEnum @doc(description: "The customer's gender")
```suggestion
    gender_v2: CustomerGenderEnum @doc(description: "The customer's gender")
```

2019-09-24 18:58 UTC, lenaorobei commented on app/code/Magento/CustomerGraphQl/etc/graphql/di.xml
> +    <preference for="Magento\CustomerGraphQl\Api\DataMapperInterface" type="Magento\CustomerGraphQl\Model\Customer\DataMapper\DataMapperPool"/>
Some logic here is redundant. Please have a look at `Magento/BundleGraphQl/etc/graphql/di.xml:27` as example.

2019-09-24 18:58 UTC, lenaorobei commented on dev/tests/integration/testsuite/Magento/Customer/_files/customer.php
> +
This file is used in many other tests. If you need some specific customer behaviour, please create new fixture.

2019-09-25 07:30 UTC, strell commented
@lenaorobei thank you for you cr, yeah, I just have found out that Magento has such kind of mapper under Magento\Framework\GraphQl\ already, so I will refactor my code using this mapper.

2019-09-26 08:17 UTC, fooman commented
It might not be the best place for this discussion but I feel using an Enum here for the list of genders makes us less inclusive. Example article here https://www.itspronouncedmetrosexual.com/2012/06/how-can-i-make-the-gender-question-on-an-application-form-more-inclusive/ 

I would generally consider best practice (if you even have to ask) to include a freeform entry. Switching to Enum would not allow for this. But still maybe a good discussion to have before needing to do gender_v3.

2019-10-23 22:07 UTC, lenaorobei commented
Closing this PR due to inactivity. @strell please feel free to reassign the issue and reopen this PR if you are interested to continue working on it.
Thank you.

2019-10-23 22:07 UTC, closed without merging