[Wishlist] Remove name from WishlistOutput #920
magento/graphql-ce pull request #957
Opened 2019-09-23 05:18 UTC by XxXgeoXxX

### Description (*)
Original issue: https://github.com/magento/graphql-ce/issues/920

### Questions or comments
1. Should we create separate resolver for Customer instead use Wishlist resolver?
2. Should we deprecated query 'Wishlists'?

Note: I'm working to coverage this mutation by functional tests.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2019-10-07 09:05 UTC, lenaorobei commented on app/code/Magento/WishlistGraphQl/Model/Resolver/CustomerWishlistsResolver.php
> +        if (0 === count($wishlists)) {
Please use `getSize` method instead.

2019-10-07 09:09 UTC, lenaorobei commented on app/code/Magento/WishlistGraphQl/Model/Resolver/CustomerWishlistsResolver.php
> +        if (!$customerId && 0 === $customerId) {
`0 === $customerId` is already covered by `!$customerId` check. Please make check more specific.

2019-10-07 09:11 UTC, lenaorobei commented on app/code/Magento/WishlistGraphQl/etc/schema.graphqls
> +     items: [WishlistItem] @deprecated(reason: "Use field `items` from type `Wishlist` instead") @resolver(class: "\\Magento\\WishlistGraphQl\\Model\\Resolver\\WishlistItemsResolver") @doc(descriptio
```suggestion
    items: [WishlistItem] @deprecated(reason: "Use field `items` from type `Wishlist` instead") @resolver(class: "\\Magento\\WishlistGraphQl\\Model\\Resolver\\WishlistItemsResolver") @doc(description: "An array of items in the customer's wish list"),
```

2019-10-07 09:14 UTC, lenaorobei requested changes
Please move the logic for getting customer wish list to the separate class with `execute` method and use it in both places - where array of wishlists and single wish list is returned.

2019-10-24 16:31 UTC, lenaorobei approved these changes

2019-10-24 16:32 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-6165](https://jira.corp.magento.com/browse/ENGCOM-6165) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

2019-10-29 19:06 UTC, lenaorobei commented
fixed https://github.com/magento/graphql-ce/issues/1038

2019-10-30 19:30 UTC, lenaorobei approved these changes

2019-10-30 19:32 UTC, magento-engcom-team commented
Hi @lenaorobei, thank you for the review.
[ENGCOM-6165](https://jira.corp.magento.com/browse/ENGCOM-6165) has been created to process this Pull Request

2019-11-01 21:46 UTC, merged